const fs = require("fs"), path = require("path"), vm = require("vm"), assert = require("assert");
const root = path.resolve(__dirname, ".."), storage = new Map(), nodes = new Map(), listeners = {};
let now = 1700000000000;
function node(id) {
  if (!nodes.has(id)) nodes.set(id, { innerHTML: "", textContent: "", value: "1", classList: { toggle() {} }, querySelectorAll: () => [], addEventListener() {} });
  return nodes.get(id);
}
const document = { getElementById: node, querySelector: node, querySelectorAll: () => [], addEventListener(type, handler) { listeners[type] = handler; } };
const context = vm.createContext({ window: {}, document, Date, Math, Blob, console, setTimeout: () => 0, clearTimeout() {}, setInterval: () => 0,
  localStorage: { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) } });
for (const [, file] of fs.readFileSync(path.join(root, "index.html"), "utf8").matchAll(/src="([^"]+\.js)"/g)) {
  if (file === "js/main.js") continue;
  vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context, { filename: file });
  if (file === "js/runtime.js") context.window.GameRuntime.configure({ now: () => now, random: () => .5 });
}
const game = context.window;
const html = () => node("app").innerHTML;
async function click(action, data = {}) {
  const button = { dataset: { action, ...data }, classList: { contains: () => false } };
  await listeners.click({ target: { closest: () => button } });
}
async function run() {
  game.UI.init(); game.UI.navigate("party");
  assert(html().includes("冒険の準備") && html().includes("パーティを編成する") && html().includes("直近ログ"));
  assert(html().includes('data-action="rename-party" data-party="0"') && html().includes("名前を変更"), "The party name is editable from the overview");
  assert(!html().includes("募集要項") && !html().includes("LATEST REPORT"));
  await click("rename-party", { party: "0" });
  assert(node("modal-root").innerHTML.includes("第1パーティの名前を変更"));
  await listeners.submit({ target: { id: "party-name-form", dataset: { party: "0" }, elements: { name: { value: "風読み隊" } } }, preventDefault() {} });
  assert.strictEqual(game.Party.name(0), "風読み隊");
  assert(html().includes("風読み隊"), "The renamed party is immediately updated in the overview");
  await click("party-view", { view: "adventure" });
  assert(html().includes("出撃する仲間を選んでください"));
  await click("party-view", { view: "formation" });
  assert(html().includes("風読み隊 — メンバー編成"), "The saved party name is shown in the detail header");
  assert(!html().includes('data-action="rename-party"'), "The formation route no longer contains a separate rename action");
  const a = require("./helpers").createCharacter(game, "先頭の戦士", "warrior", "human", "merchant").id;
  const b = require("./helpers").createCharacter(game, "後衛の魔術師", "mage", "human", "scholar").id;
  const c = require("./helpers").createCharacter(game, "控え1").id;
  const d = require("./helpers").createCharacter(game, "控え2").id;
  game.Characters.get(a).level = 30;
  node(".main-area").scrollTop = 360;
  await click("toggle-party", { character: a });
  assert.strictEqual(node(".main-area").scrollTop, 360, "Adding a member from the roster should preserve the formation viewport");
  assert(html().includes("獲得・探索補正"), "Formation shows its acquisition section");
  assert(html().includes("危険察知"), "Formation lists the acquisition skill source");
  assert(html().includes("取得金額 ×1.08 +5G"), "Formation shows the combined acquisition bonus");
  assert(html().includes('data-action="roster-scope" data-scope="party"') && html().includes("編成中 1"), "Formation offers a compact shortcut to current members");
  await click("roster-scope", { scope: "party" });
  assert(html().includes("先頭の戦士") && !html().includes("後衛の魔術師"), "Current-member scope hides unassigned adventurers");
  await click("roster-scope", { scope: "all" });
  assert(html().includes("後衛の魔術師"), "All-adventurer scope restores the full roster");
  await click("roster-scope", { scope: "available" });
  const waitingRoster = html().slice(html().indexOf('<div class="roster-list">'), html().indexOf('<nav class="pagination"'));
  assert(html().includes("待機中 3") && waitingRoster.includes("後衛の魔術師") && !waitingRoster.includes("先頭の戦士"), "Waiting scope shows only adventurers who can join a party");
  await click("roster-scope", { scope: "all" });
  node(".main-area").scrollTop = 420;
  await listeners.change({ target: { hasAttribute: key => key === "data-roster-filter", dataset: { rosterFilter: "sort" }, value: "name" } });
  assert.strictEqual(node(".main-area").scrollTop, 420, "Detailed roster filters should preserve the formation viewport");
  assert(html().includes("全員・全職業・名前順"), "Collapsed roster filters summarize the current conditions");
  node("party-roster-query").value = "存在しない名前";
  await listeners.submit({ target: { id: "party-roster-form" }, preventDefault() {} });
  assert(html().includes("条件に合う冒険者はいません。") && html().includes('data-action="reset-roster-filters"'), "An empty roster provides a direct recovery action");
  await click("reset-roster-filters");
  assert(html().includes("全員・全職業・レベル順") && html().includes("先頭の戦士"), "Resetting restores the complete roster and default order");
  assert(html().includes('data-action="party-action-preset"') && html().includes("行動率を一括設定"));
  await click("party-action-preset", { preset: "physical" });
  assert.deepStrictEqual(JSON.parse(JSON.stringify(game.Characters.get(a).actionRates)), { attack: 100, technique: 100, spell: 0, healing: 30 });
  assert(html().includes("行動 物理重視"), "Formation summarizes each member's action-rate profile");
  await click("open-equipment", { character: a });
  assert(node("modal-root").innerHTML.includes('class="action-rate-form" data-character="' + a + '"'));
  assert(node("modal-root").innerHTML.includes('data-action="action-rate-preset"') && node("modal-root").innerHTML.includes("物理重視") && node("modal-root").innerHTML.includes("回復重視"));
  assert(node("modal-root").innerHTML.includes('type="range"') && node("modal-root").innerHTML.includes("data-action-rate-value"), "Action rates use the same slider UI in the equipment route");
  assert(!node("modal-root").innerHTML.includes('class="action-rate-form" data-character="' + b + '"'), "Only the opened character appears in the equipment screen");
  await click("close-modal");
  assert(game.Items.equip(a, "item-1").ok); game.UI.render();
  await click("open-equipment", { character: a });
  assert(node("modal-root").innerHTML.includes('data-action="unequip" data-character="' + a + '" data-instance="item-1"'));
  await click("unequip", { character: a, instance: "item-1" });
  assert.strictEqual(game.Characters.get(a).equipment.length, 0);
  await click("close-modal");
  assert(game.Presets.save(0, "戦士単独").ok);
  game.UI.render();
  assert(html().includes("現在と同じ") && html().includes("現在の隊列・装備・行動率と一致しています。") && html().includes('disabled>適用済み</button>'), "The matching preset is identifiable and cannot be redundantly applied");
  assert(html().includes('id="preset-name" required maxlength="24" placeholder="洞窟攻略用など" value="戦士単独"') && html().includes('id="preset-save-button"') && html().includes("上書き内容を確認"), "The selected occupied slot should expose its current name and overwrite action");
  await listeners.change({ target: { id: "preset-slot", value: "1", hasAttribute: () => false } });
  assert.strictEqual(node("preset-name").value, "");
  assert.strictEqual(node("preset-save-button").textContent, "新規保存");
  assert(game.Presets.save(1, "後衛編成").ok);
  game.UI.render();
  assert(html().includes('<option value="1" selected>2：後衛編成</option>') && html().includes('value="後衛編成"'), "The selected preset slot should remain active after rendering");
  await listeners.change({ target: { id: "preset-slot", value: "0", hasAttribute: () => false } });
  assert.strictEqual(node("preset-name").value, "戦士単独");
  assert.strictEqual(node("preset-save-button").textContent, "上書き内容を確認");
  assert(game.Items.equip(a, "item-1").ok);
  game.Characters.setActionRates(a, { attack: 100, technique: 100, spell: 100, healing: 100 });
  game.UI.render();
  assert(html().includes("この編成を呼び出す") && !html().includes('disabled>適用済み</button>'), "Changing equipment or action rates makes the preset available again");
  await click("request-preset", { kind: "apply", slot: "0" });
  assert(node("modal-root").innerHTML.includes("呼び出し前の変更確認") && node("modal-root").innerHTML.includes("装備 1点 → 0点") && node("modal-root").innerHTML.includes("外す：木の剣") && node("modal-root").innerHTML.includes("行動率"), "Preset confirmation should show factual lineup, equipment and action-rate changes before applying");
  node(".main-area").scrollTop = 480;
  await click("confirm-preset");
  assert.strictEqual(node(".main-area").scrollTop, 480, "Applying a preset should keep the formation viewport in place");
  assert(game.Presets.matches(0));
  assert(html().includes("メンバー編成") && html().includes("編成プリセットを保存・呼び出し"));
  assert(html().includes("出撃先指定") && html().includes("出撃先を指定する") && !html().includes("この編成で出撃する"));
  await click("toggle-party", { character: b }); await click("toggle-party", { character: c });
  assert(html().includes("人数上限"));
  const overflow = html().match(new RegExp('<button class="roster-quick-action[^>]*data-character="' + d + '"[^>]*>'));
  assert(overflow && overflow[0].includes("disabled"));
  await click("move-party", { character: b, direction: "-1" });
  assert.strictEqual(game.Party.ids()[0], b);
  await click("toggle-party", { character: c });
  node("preset-slot").value = "0"; node("preset-name").value = "二人編成";
  await listeners.submit({ target: { id: "preset-form" }, preventDefault() {} });
  assert(node("modal-root").innerHTML.includes("上書き前の変更確認") && node("modal-root").innerHTML.includes("新たに保存 → 1番") && node("modal-root").innerHTML.includes("隊列 1番 → 2番"), "Overwriting a preset should preview additions and formation changes before confirmation");
  await click("close-modal");
  game.Items.add("sticky_fluid", 1);
  assert((await game.GameClient.execute("encyclopedia.trackItem", { itemId: "sticky_fluid" })).ok);
  await click("party-view", { view: "adventure" });
  assert(html().includes("DEPARTURE PARTY") && html().includes("先頭の戦士") && html().includes("後衛の魔術師"));
  assert(html().includes("風読み隊 · 2/"), "The party name is reused in the departure summary");
  assert(html().includes("獲得・探索補正") && html().includes("魔術理論") && html().includes("後衛の魔術師の経験値 ×1.12"), "Departure screen repeats the acquisition effects that will be snapshotted");
  assert(html().indexOf("DEPARTURE PARTY") < html().indexOf("dungeon-grid"));
  assert(html().includes('data-action="select-dungeon"') && html().includes("この攻略先へ出撃") && html().includes("選択中の攻略先"));
  assert(html().includes('<details class="dungeon-details"') && html().includes("依頼・噂・現地記録を見る"));
  assert(html().includes("探索目標") && html().includes("ねばねばした液体") && html().includes("探索目標の記録あり") && html().includes("1種の魔物"), "A tracked discovery marks matching destination records without exposing drop rates");
  assert(!html().includes("攻略目安") && !html().includes("次の挑戦へのヒント"));
  assert(html().includes('data-action="select-dungeon-chapter"') && html().includes("data-dungeon-chapter-select") && html().includes("1〜5 / 16章を表示") && html().includes("本編攻略 0/5"), "Destination routes use a compact nearby tab set plus an all-chapter selector");
  assert(!html().includes("燐光の洞窟"), "Only the active chapter routes are rendered");
  await click("select-dungeon-chapter", { chapter: "seal" });
  assert(html().includes("燐光の洞窟") && html().includes("第2章：地下の封印"), "Past and future chapters can be inspected");
  await listeners.change({ target: { hasAttribute: key => key === "data-dungeon-chapter-select", value: "roadside" } });
  assert(html().includes("風鳴りの草原") && html().includes("第1章：街道の異変"), "The native chapter selector changes the displayed route chapter");
  await click("select-dungeon-chapter", { chapter: "roadside" });
  assert(html().includes("次の攻略先") && html().includes("寄り道・高難度") === false, "The next main route is highlighted and optional routes stay separated");
  await listeners.change({ target: { hasAttribute: key => key === "data-exploration-dungeon", dataset: { explorationDungeon: "meadow" }, value: "5" } });
  await click("party-view", { view: "formation" }); await click("party-view", { view: "adventure" });
  assert(html().includes('<option value="5" selected>5倍'));
  assert.deepStrictEqual(JSON.parse(JSON.stringify(game.Party.plan(0))), { dungeonId: "meadow", difficultyId: "normal", timeMultiplier: 5 }, "Destination settings are saved per party");
  require("./helpers").completeThrough(game, "seal");
  game.GameState.data.unlockedPartyCount = 2;
  await click("party-open", { party: "1", view: "formation" }); await click("toggle-party", { character: d });
  await click("party-view", { view: "adventure" });
  assert(html().includes('<option value="1" selected>1倍'));
  await click("select-dungeon-chapter", { chapter: "roadside" });
  await click("select-dungeon", { dungeon: "meadow" });
  await listeners.change({ target: { hasAttribute: key => key === "data-exploration-dungeon", dataset: { explorationDungeon: "meadow" }, value: "3" } });
  await click("party-open", { party: "0", view: "adventure" });
  assert(html().includes('<option value="5" selected>5倍'));
  await click("quick-start-party", { party: "0" });
  assert.strictEqual(game.GameState.data.expeditions[0].timeMultiplier, 5);
  assert(html().includes('data-countdown="0"') && html().includes("このパーティは探索中"));
  const started = JSON.stringify(game.GameState.data.expeditions[0]);
  await click("quick-start-party", { party: "0" });
  assert.strictEqual(JSON.stringify(game.GameState.data.expeditions[0]), started, "Repeated departure must not overwrite the expedition");
  await click("party-view", { view: "formation" });
  const ids = game.Party.ids().join(",");
  await click("toggle-party", { character: a });
  assert.strictEqual(game.Party.ids().join(","), ids, "Busy party membership is protected");
  now = game.GameState.data.expeditions[0].endsAt; await game.GameClient.execute("expedition.collect");
  await click("party-view", { view: "results" });
  assert(html().includes("LATEST REPORT") && html().includes("最新の探索報告"));
  assert(!html().includes("party-list") && !html().includes("dungeon-grid"));
  const previousResult = game.Party.result(0);
  assert(html().includes("直前の探索条件") && html().includes(`${previousResult.timeMultiplier}倍探索`) && html().includes('data-action="repeat-expedition"'), "The report offers one manual repeat using the completed expedition settings");
  await click("repeat-expedition");
  assert(game.GameState.data.expeditions[0] && game.GameState.data.expeditions[0].dungeonId === previousResult.dungeonId && game.GameState.data.expeditions[0].difficultyId === previousResult.difficultyId && game.GameState.data.expeditions[0].timeMultiplier === previousResult.timeMultiplier, "Manual repeat preserves destination, difficulty and duration multiplier");
  assert(html().includes("再探索中") && html().includes("探索ログを見る") && !html().includes('data-action="repeat-expedition"'), "The report stays open and shows the active repeat without starting another run automatically");
  await click("party-open", { party: "1", view: "adventure" });
  assert(html().includes('<option value="3" selected>3倍'));
  await click("select-dungeon", { dungeon: "cave" });
  await click("party-back");
  assert(html().includes("攻略先：燐光の洞窟 · 1倍探索"), "Party top shows the destination selected in party details");
  await click("quick-start-party", { party: "1" });
  assert.strictEqual(game.GameState.data.expeditions[1].dungeonId, "cave", "Party top departure starts the selected destination");
  assert(html().includes("冒険の準備") && html().includes('data-party-overview="1"') && !html().includes("LIVE ADVENTURE LOG"), "Party top departure stays on the overview");
  console.log("Party workflow test passed: separated tasks, inline departure, compact settings, capacity/busy guards, formation edits, party-specific duration, summary/results isolation and duplicate departure protection");
}
run().catch(error => { console.error(error); process.exitCode = 1; });
