const fs = require("fs"), path = require("path"), vm = require("vm"), assert = require("assert");
const root = path.resolve(__dirname, ".."), storage = new Map(), nodes = new Map(), listeners = {};
let now = 1700000000000;
function node(id) {
  if (!nodes.has(id)) nodes.set(id, { innerHTML: "", textContent: "", value: "1", classList: { toggle() {} }, querySelectorAll: () => [], addEventListener() {} });
  return nodes.get(id);
}
const document = { getElementById: node, querySelector: node, querySelectorAll: () => [], addEventListener(type, handler) { listeners[type] = handler; } };
const context = vm.createContext({ window: {}, document, Date, Math, Blob, console, setTimeout: () => 0, clearTimeout() {}, setInterval: () => 0,
  localStorage: { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) } });
for (const [, file] of fs.readFileSync(path.join(root, "index.html"), "utf8").matchAll(/src="([^"]+\.js)"/g)) {
  if (file === "js/main.js") continue;
  vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context, { filename: file });
  if (file === "js/runtime.js") context.window.GameRuntime.configure({ now: () => now, random: () => .5 });
}
const game = context.window;
const html = () => node("app").innerHTML;
async function click(action, data = {}) {
  const button = { dataset: { action, ...data }, classList: { contains: () => false } };
  await listeners.click({ target: { closest: () => button } });
}
async function run() {
  game.UI.init(); game.UI.navigate("party");
  assert(html().includes("冒険の準備") && html().includes("パーティを編成する") && html().includes("直近ログ"));
  assert(html().includes('data-action="rename-party" data-party="0"') && html().includes("名前を変更"), "The party name is editable from the overview");
  assert(!html().includes("募集要項") && !html().includes("LATEST REPORT"));
  await click("rename-party", { party: "0" });
  assert(node("modal-root").innerHTML.includes("第1パーティの名前を変更"));
  await listeners.submit({ target: { id: "party-name-form", dataset: { party: "0" }, elements: { name: { value: "風読み隊" } } }, preventDefault() {} });
  assert.strictEqual(game.Party.name(0), "風読み隊");
  assert(html().includes("風読み隊"), "The renamed party is immediately updated in the overview");
  await click("party-view", { view: "adventure" });
  assert(html().includes("出撃する仲間を選んでください"));
  await click("party-view", { view: "formation" });
  assert(html().includes("風読み隊 — メンバー編成"), "The saved party name is shown in the detail header");
  assert(!html().includes('data-action="rename-party"'), "The formation route no longer contains a separate rename action");
  const a = require("./helpers").createCharacter(game, "先頭の戦士", "warrior", "human", "merchant").id;
  const b = require("./helpers").createCharacter(game, "後衛の魔術師", "mage", "human", "scholar").id;
  const c = require("./helpers").createCharacter(game, "控え1").id;
  const d = require("./helpers").createCharacter(game, "控え2").id;
  game.Characters.get(a).level = 30;
  await click("toggle-party", { character: a });
  assert(html().includes("獲得・探索補正"), "Formation shows its acquisition section");
  assert(html().includes("危険察知"), "Formation lists the acquisition skill source");
  assert(html().includes("取得金額 ×1.08 +5G"), "Formation shows the combined acquisition bonus");
  assert(html().includes('data-action="party-action-preset"') && html().includes("行動率を一括設定"));
  await click("party-action-preset", { preset: "physical" });
  assert.deepStrictEqual(JSON.parse(JSON.stringify(game.Characters.get(a).actionRates)), { attack: 100, technique: 100, spell: 0, healing: 30 });
  assert(html().includes("行動 物理重視"), "Formation summarizes each member's action-rate profile");
  await click("open-equipment", { character: a });
  assert(node("modal-root").innerHTML.includes('class="action-rate-form" data-character="' + a + '"'));
  assert(node("modal-root").innerHTML.includes('data-action="action-rate-preset"') && node("modal-root").innerHTML.includes("物理重視") && node("modal-root").innerHTML.includes("回復重視"));
  assert(node("modal-root").innerHTML.includes('type="range"') && node("modal-root").innerHTML.includes("data-action-rate-value"), "Action rates use the same slider UI in the equipment route");
  assert(!node("modal-root").innerHTML.includes('class="action-rate-form" data-character="' + b + '"'), "Only the opened character appears in the equipment screen");
  await click("close-modal");
  assert(game.Items.equip(a, "item-1").ok); game.UI.render();
  await click("open-equipment", { character: a });
  assert(node("modal-root").innerHTML.includes('data-action="unequip" data-character="' + a + '" data-instance="item-1"'));
  await click("unequip", { character: a, instance: "item-1" });
  assert.strictEqual(game.Characters.get(a).equipment.length, 0);
  await click("close-modal");
  assert(html().includes("メンバー編成") && html().includes("編成プリセットを保存・呼び出し"));
  assert(html().includes("出撃先指定") && html().includes("出撃先を指定する") && !html().includes("この編成で出撃する"));
  await click("toggle-party", { character: b }); await click("toggle-party", { character: c });
  assert(html().includes("人数上限"));
  const overflow = html().match(new RegExp('<button class="roster-quick-action[^>]*data-character="' + d + '"[^>]*>'));
  assert(overflow && overflow[0].includes("disabled"));
  await click("move-party", { character: b, direction: "-1" });
  assert.strictEqual(game.Party.ids()[0], b);
  await click("toggle-party", { character: c });
  await click("party-view", { view: "adventure" });
  assert(html().includes("DEPARTURE PARTY") && html().includes("先頭の戦士") && html().includes("後衛の魔術師"));
  assert(html().includes("風読み隊 · 2/"), "The party name is reused in the departure summary");
  assert(html().includes("獲得・探索補正") && html().includes("魔術理論") && html().includes("後衛の魔術師の経験値 ×1.12"), "Departure screen repeats the acquisition effects that will be snapshotted");
  assert(html().indexOf("DEPARTURE PARTY") < html().indexOf("dungeon-grid"));
  assert(html().includes('data-action="select-dungeon"') && html().includes("この攻略先へ出撃") && html().includes("選択中の攻略先"));
  assert(html().includes('<details class="dungeon-details"') && html().includes("依頼・噂・現地記録を見る"));
  assert(!html().includes("攻略目安") && !html().includes("次の挑戦へのヒント"));
  assert(html().includes('data-action="select-dungeon-chapter"') && html().includes("data-dungeon-chapter-select") && html().includes("1〜5 / 15章を表示") && html().includes("本編攻略 0/5"), "Destination routes use a compact nearby tab set plus an all-chapter selector");
  assert(!html().includes("燐光の洞窟"), "Only the active chapter routes are rendered");
  await click("select-dungeon-chapter", { chapter: "seal" });
  assert(html().includes("燐光の洞窟") && html().includes("第2章：地下の封印"), "Past and future chapters can be inspected");
  await listeners.change({ target: { hasAttribute: key => key === "data-dungeon-chapter-select", value: "roadside" } });
  assert(html().includes("風鳴りの草原") && html().includes("第1章：街道の異変"), "The native chapter selector changes the displayed route chapter");
  await click("select-dungeon-chapter", { chapter: "roadside" });
  assert(html().includes("次の攻略先") && html().includes("寄り道・高難度") === false, "The next main route is highlighted and optional routes stay separated");
  await listeners.change({ target: { hasAttribute: key => key === "data-exploration-dungeon", dataset: { explorationDungeon: "meadow" }, value: "5" } });
  await click("party-view", { view: "formation" }); await click("party-view", { view: "adventure" });
  assert(html().includes('<option value="5" selected>5倍'));
  assert.deepStrictEqual(JSON.parse(JSON.stringify(game.Party.plan(0))), { dungeonId: "meadow", difficultyId: "normal", timeMultiplier: 5 }, "Destination settings are saved per party");
  require("./helpers").completeThrough(game, "seal");
  game.GameState.data.unlockedPartyCount = 2;
  await click("party-open", { party: "1", view: "formation" }); await click("toggle-party", { character: d });
  await click("party-view", { view: "adventure" });
  assert(html().includes('<option value="1" selected>1倍'));
  await click("select-dungeon-chapter", { chapter: "roadside" });
  await click("select-dungeon", { dungeon: "meadow" });
  await listeners.change({ target: { hasAttribute: key => key === "data-exploration-dungeon", dataset: { explorationDungeon: "meadow" }, value: "3" } });
  await click("party-open", { party: "0", view: "adventure" });
  assert(html().includes('<option value="5" selected>5倍'));
  await click("quick-start-party", { party: "0" });
  assert.strictEqual(game.GameState.data.expeditions[0].timeMultiplier, 5);
  assert(html().includes('data-countdown="0"') && html().includes("このパーティは探索中"));
  const started = JSON.stringify(game.GameState.data.expeditions[0]);
  await click("quick-start-party", { party: "0" });
  assert.strictEqual(JSON.stringify(game.GameState.data.expeditions[0]), started, "Repeated departure must not overwrite the expedition");
  await click("party-view", { view: "formation" });
  const ids = game.Party.ids().join(",");
  await click("toggle-party", { character: a });
  assert.strictEqual(game.Party.ids().join(","), ids, "Busy party membership is protected");
  now = game.GameState.data.expeditions[0].endsAt; await game.GameClient.execute("expedition.collect");
  await click("party-view", { view: "results" });
  assert(html().includes("LATEST REPORT") && html().includes("最新の探索報告"));
  assert(!html().includes("party-list") && !html().includes("dungeon-grid"));
  await click("party-open", { party: "1", view: "adventure" });
  assert(html().includes('<option value="3" selected>3倍'));
  await click("select-dungeon", { dungeon: "cave" });
  await click("party-back");
  assert(html().includes("攻略先：燐光の洞窟 · 1倍探索"), "Party top shows the destination selected in party details");
  await click("quick-start-party", { party: "1" });
  assert.strictEqual(game.GameState.data.expeditions[1].dungeonId, "cave", "Party top departure starts the selected destination");
  assert(html().includes("冒険の準備") && html().includes('data-party-overview="1"') && !html().includes("LIVE ADVENTURE LOG"), "Party top departure stays on the overview");
  console.log("Party workflow test passed: separated tasks, inline departure, compact settings, capacity/busy guards, formation edits, party-specific duration, summary/results isolation and duplicate departure protection");
}
run().catch(error => { console.error(error); process.exitCode = 1; });
