const fs = require("fs"), vm = require("vm"), path = require("path"), assert = require("assert");
const root = path.resolve(__dirname, ".."), storage = new Map();
let now = 1700000000000, failSave = false;
function load() {
  const context = vm.createContext({ window: {}, Date, Math, Blob, console: { ...console, warn() {} } });
  const scripts = Array.from(fs.readFileSync(path.join(root, "index.html"), "utf8").matchAll(/src="([^"]+\.js)"/g), match => match[1]).filter(file => !["js/ui.js", "js/main.js"].includes(file));
  for (const file of scripts) {
    vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context, { filename: file });
    if (file === "js/runtime.js") context.window.GameRuntime.configure({ now: () => now, random: () => .5 });
    if (file === "js/storage.js") context.window.SaveStorage.use({ get: key => storage.get(key) || null, set: (key, value) => { if (failSave) throw Error("full"); storage.set(key, value); }, remove: key => storage.delete(key) });
  }
  return context.window;
}
let game = load();
async function run() {
  assert(!(await game.GameClient.execute("preset.save", { slot: 0, name: "空" })).ok);
  const a = require("./helpers").createCharacter(game, "戦士", "warrior", "human", "common").id;
  const b = require("./helpers").createCharacter(game, "盗賊", "thief", "human", "common").id;
  const c = require("./helpers").createCharacter(game, "控え", "warrior", "human", "common").id;
  game.Characters.get(a).level = 20; game.Characters.get(b).level = 20;
  game.Party.toggle(a); game.Party.toggle(b);
  const iron = game.Items.add("iron_sword", 1, { source: "shop" }).instances[0].id;
  game.Items.equip(a, "item-1"); game.Items.equip(a, "item-2"); game.Items.equip(b, iron);
  game.Items.setLocked("item-1", true);
  game.Characters.setActionRates(a, { attack: 10, technique: 10, spell: 10, healing: 70 }); game.Characters.setActionRates(b, { attack: 60, technique: 30, spell: 10, healing: 0 });
  assert(!(await game.GameClient.execute("preset.save", { slot: 6, name: "範囲外" })).ok);
  assert(!(await game.GameClient.execute("preset.save", { slot: 0, name: " " })).ok);
  assert((await game.GameClient.execute("preset.save", { slot: 0, name: "草原用" })).ok);
  assert(game.Presets.lineupMatches(0), "A saved preset recognizes the same ordered lineup");
  assert(game.Presets.matches(0), "A freshly saved preset matches the current party");
  const snapshot = JSON.stringify(game.Presets.slots()[0]);
  game.GameState.data.parties[0].reverse();
  game.Characters.get(a).equipment = [iron, "item-2"]; game.Characters.get(b).equipment = ["item-1"];
  game.Characters.setActionRates(a, { attack: 100, technique: 0, spell: 0, healing: 0 }); game.Characters.setActionRates(b, { attack: 0, technique: 100, spell: 0, healing: 0 });
  assert(!game.Presets.lineupMatches(0), "Changing member order no longer matches the saved lineup");
  assert(!game.Presets.matches(0), "Lineup, equipment or action-rate changes make the preset different");
  assert.strictEqual(JSON.stringify(game.Presets.slots()[0]), snapshot, "Presets are detached snapshots.");
  const before = JSON.stringify(game.GameState.data);
  failSave = true;
  assert(!(await game.GameClient.execute("preset.apply", { slot: 0 })).ok);
  failSave = false;
  assert.strictEqual(JSON.stringify(game.GameState.data), before, "Rollback restores gear/order/policies together.");
  assert((await game.GameClient.execute("preset.apply", { slot: 0 })).ok);
  assert(game.Presets.matches(0), "Applying a preset restores an exact match");
  assert.strictEqual(game.Party.ids().join(","), [a, b].join(","));
  assert.strictEqual(game.Characters.get(a).equipment[0], "item-1");
  assert.strictEqual(game.Characters.get(b).equipment[0], iron);
  assert.strictEqual(game.Characters.get(a).actionRates.healing, 70);
  assert.strictEqual(game.Characters.get(b).actionRates.attack, 60);
  assert(game.Items.getInstance("item-1").locked);
  assert(game.SaveTransfer.parse(JSON.stringify(game.GameState.data)).ok);
  game = load();
  assert.strictEqual(JSON.stringify(game.Presets.slots()[0]), snapshot);
  game.Items.unequip(a, "item-1"); game.Items.equip(c, "item-1");
  assert(!game.Presets.check(0).ok && game.Presets.check(0).message.includes("控え"));
  const conflict = JSON.stringify(game.GameState.data);
  assert(!(await game.GameClient.execute("preset.apply", { slot: 0 })).ok);
  assert.strictEqual(JSON.stringify(game.GameState.data), conflict);
  game.Items.unequip(c, "item-1");
  const maxWeight = game.Characters.maxWeight;
  game.Characters.maxWeight = () => 0;
  assert(!game.Presets.check(0).ok && game.Presets.check(0).message.includes("重量"));
  game.Characters.maxWeight = maxWeight;
  assert(!(await game.GameClient.execute("preset.apply", { slot: 0, partyIndex: 1 })).ok);
  require("./helpers").completeThrough(game, "seal");
  game.GameState.data.unlockedPartyCount = 2;
  game.GameState.data.parties[0] = [a]; game.GameState.data.parties[1] = [b];
  assert(!game.Presets.check(0, 0).ok && !game.Presets.check(0, 1).ok);
  game.GameState.data.parties[0] = []; game.GameState.data.parties[1] = [];
  assert((await game.GameClient.execute("preset.apply", { slot: 0, partyIndex: 1 })).ok);
  assert.strictEqual(game.Party.ids(1).join(","), [a, b].join(","));
  assert((await game.GameClient.execute("expedition.start", { dungeonId: "meadow", partyIndex: 1 })).ok);
  assert(!(await game.GameClient.execute("preset.save", { slot: 1, name: "探索中", partyIndex: 1 })).ok);
  assert(!(await game.GameClient.execute("preset.apply", { slot: 0, partyIndex: 1 })).ok);
  assert(!(await game.GameClient.execute("preset.apply", { slot: 0, partyIndex: 0 })).ok);
  now += 30000; await game.GameClient.execute("expedition.collect");
  game.Items.unequip(a, "item-1"); game.Items.setLocked("item-1", false);
  assert(game.Items.sell("item-1").ok);
  assert(!game.Presets.check(0, 1).ok && game.Presets.check(0, 1).message.includes("ありません"));
  const saved = JSON.stringify(game.GameState.data);
  assert(game.SaveTransfer.parse(saved).ok, "Sold gear may remain referenced by a stale preset.");
  const bad = JSON.parse(saved); bad.presets.slots[0].members[1].characterId = a;
  assert(!game.SaveTransfer.parse(JSON.stringify(bad)).ok);
  const badGear = JSON.parse(saved); badGear.presets.slots[0].members[0].equipment[0] = "item-999999";
  assert(!game.SaveTransfer.parse(JSON.stringify(badGear)).ok);
  const badPolicy = JSON.parse(saved); badPolicy.presets.slots[0].members[0].actionRates.attack = 999;
  assert(!game.SaveTransfer.parse(JSON.stringify(badPolicy)).ok);
  assert(game.SaveTransfer.restore(game.SaveTransfer.parse(saved).state).ok);
  assert.strictEqual(JSON.stringify(game.Presets.slots()[0]), snapshot);
  assert((await game.GameClient.execute("preset.save", { slot: 0, name: "新しい装備", partyIndex: 1 })).ok);
  assert.strictEqual(game.Presets.slots()[0].members[0].equipment.includes("item-1"), false);
  const characters = JSON.stringify(game.GameState.data.characters);
  assert((await game.GameClient.execute("preset.delete", { slot: 0 })).ok);
  assert.strictEqual(JSON.stringify(game.GameState.data.characters), characters);
  game.GameState.reset();
  assert(game.Presets.slots().every(slot => slot === null));
  console.log("Presets test passed: slots, detached snapshots, order/gear/policy restore, swaps, locked gear, conflicts/missing gear/weight/busy guards, atomic rollback, both parties, persistence/import/reset");
}
run().catch(error => { console.error(error); process.exitCode = 1; });
