const fs = require("fs");
const path = require("path");
const vm = require("vm");
const assert = require("assert");
const storage = new Map();
let failKey = null, clicked = 0, revoked = 0;
const context = vm.createContext({ console, window: {}, Date, Math, Blob, setTimeout: fn => fn(),
  URL: { createObjectURL: blob => { assert(blob instanceof Blob); return "blob:test"; }, revokeObjectURL: () => revoked++ },
  document: { body: { appendChild: () => {} }, createElement: () => ({ click: () => clicked++, remove: () => {} }) },
  localStorage: { getItem: key => storage.get(key) || null, setItem: (key, value) => { if (key === failKey) throw new Error("quota"); storage.set(key, value); }, removeItem: key => storage.delete(key) }
});
["data/masterSchema.js", "data/items.js", "data/facilities.js", "data/qualities.js", "data/equipmentSkills.js", "data/equipmentSets.js", "data/skills.js", "data/jobs.js", "data/origins.js", "data/affinities.js", "data/skillGrants.js", "data/portraits.js", "data/companions.js", "data/monsters.js", "data/dungeons.js", "data/explorationEvents.js", "data/recipes.js", "data/adventurerMilestones.js", "js/runtime.js", "js/storage.js", "js/save.js", "js/gameState.js", "js/equipmentSkills.js", "js/characters.js", "js/items.js", "js/party.js", "js/monsterLoot.js", "js/exploration.js", "data/skillCategories.js", "js/skillCombat.js", "js/statusCombat.js", "js/combatMath.js", "js/combatDecision.js", "js/battle.js", "js/dungeon.js", "js/saveTransfer.js"].forEach(file => vm.runInContext(fs.readFileSync(path.join(__dirname, "..", file), "utf8"), context));
const game = context.window, transfer = game.SaveTransfer;
const created = require("./helpers").createCharacter(game, "バックアップ", "cleric", "elf", "sacred", "archer");
const fellow = require("./helpers").createCharacter(game, "旅仲間", "warrior", "human", "guard", "warrior");
game.Items.equip(created.id, "item-1");
game.Party.toggle(created.id);
game.Party.toggle(fellow.id);
game.Characters.setActionRates(created.id, { attack: 10, technique: 10, spell: 10, healing: 70 });
assert(game.Dungeon.start("meadow").ok);
const clone = () => JSON.parse(JSON.stringify(game.GameState.data));
const snapshot = clone();
{ const parsed = transfer.parse(JSON.stringify(snapshot)); assert(parsed.ok, parsed.message); }
assert(transfer.parse("\uFEFF" + JSON.stringify(snapshot)).ok);
game.GameState.data.gold = 12345;
game.GameState.save();
const previous = JSON.stringify(game.GameState.data);
assert(transfer.restore(snapshot).ok);
assert.strictEqual(game.GameState.data.gold, snapshot.gold);
assert.strictEqual(storage.get(transfer.backupKey), previous);
assert.strictEqual(game.GameState.data.expeditions[0].partySnapshot[0].actionRates.healing, 70);
assert.strictEqual(Object.keys(game.GameState.data.expeditions[0].partySnapshot[0].routeEventSuccesses).length, 0, "A departure snapshots personal route experience");
assert.strictEqual(game.GameState.data.expeditions[0].partySnapshot[0].treasureOpenings, 0, "A departure snapshots personal opening experience");
assert.strictEqual(game.Characters.get(created.id).portraitId, "archer");
transfer.download(); transfer.download(true);
assert.strictEqual(clicked, 2); assert.strictEqual(revoked, 2);
function invalid(change) {
  const bad = clone(); change(bad);
  const before = JSON.stringify(game.GameState.data), persisted = storage.get(game.SaveSystem.exportKey);
  assert(!transfer.restore(bad).ok);
  assert.strictEqual(JSON.stringify(game.GameState.data), before);
  assert.strictEqual(storage.get(game.SaveSystem.exportKey), persisted);
}
invalid(state => state.version = 99);
invalid(state => state.gold = -1);
invalid(state => state.characters[0].exp = Number.MAX_SAFE_INTEGER);
invalid(state => state.inventory.equipment.push(state.inventory.equipment[0]));
invalid(state => state.characters[0].equipment.push("item-999"));
invalid(state => state.inventory.equipment[0].templateId = "missing");
invalid(state => state.parties[0].push(created.id));
invalid(state => state.meta.nextItemId = 1);
invalid(state => state.expeditions[0].partySnapshot[0].stats.attack = "<script>");
invalid(state => state.expeditions[0].partySnapshot[0].birthId = "missing-birth");
invalid(state => state.expeditions[0].partySnapshot[0].skillIds = ["invalid"]);
invalid(state => state.expeditions[0].partySnapshot[0].routeEventSuccesses = { "missing-route-event": 5 });
invalid(state => { state.expeditions[0].partySnapshot[0].equipmentSetBonuses = [{ setId: "missing-set", count: 2, skillIds: ["set_windtrail_2"] }]; });
invalid(state => state.expeditions[0].knownCompanionMomentKeys = ["missing-moment:0"]);
invalid(state => state.expeditions[0].trackedItemId = "missing-item");
invalid(state => { state.partyPlans[0] = { dungeonId: "missing", difficultyId: "normal", timeMultiplier: 1 }; });
invalid(state => { state.partyNames[0] = " "; });
assert(!transfer.parse("{broken").ok);
assert(!transfer.parse('{"__proto__": {}}').ok);
assert(!transfer.parse(" ".repeat(transfer.MAX_BYTES + 1)).ok);
for (const key of [transfer.backupKey, game.SaveSystem.exportKey]) {
  const before = JSON.stringify(game.GameState.data), persisted = storage.get(game.SaveSystem.exportKey);
  failKey = key;
  assert(!transfer.restore(snapshot).ok);
  assert.strictEqual(JSON.stringify(game.GameState.data), before);
  assert.strictEqual(storage.get(game.SaveSystem.exportKey), persisted);
  failKey = null;
}
game.GameState.data.expeditions[0].endsAt = Date.now() - 1;
game.Dungeon.completeIfReady();
assert(transfer.parse(JSON.stringify(game.GameState.data)).ok, "戦績とドロップを含む完了データも読み込めること");
const sharedPairKey = [created.id, fellow.id].sort().join("::");
assert.strictEqual(game.GameState.data.adventurerBonds.pairs[sharedPairKey], 1, "A completed expedition persists one shared-sortie record for the pair");
game.GameState.data.adventurerBonds.pairs[sharedPairKey] = 4;
assert(game.Dungeon.start("meadow").ok);
game.GameState.data.expeditions[0].endsAt = Date.now() - 1;
game.Dungeon.completeIfReady();
assert.strictEqual(game.GameState.data.lastResult.newAdventurerBondTiers?.[0]?.sharedSorties, 5, "A return announces the exact expedition that deepened a travel relationship");
assert.strictEqual(game.GameState.data.lastResult.newAdventurerBondTiers[0].routeLabel, "歩調の合う支え");
assert.strictEqual(game.GameState.data.lastResult.newAdventurerBondTiers[0].battleLabel, "合図の通る間合い");
assert.strictEqual(game.GameState.data.partyHistory[0][0].newAdventurerBondTiers?.[0]?.sharedSorties, 5, "Relationship growth is retained in expedition history");
{ const parsed = transfer.parse(JSON.stringify(game.GameState.data)); assert(parsed.ok, `Relationship growth survives save validation: ${parsed.message}`); }
game.GameState.data.adventurerBonds.pairs[sharedPairKey] = 20;
assert(game.Dungeon.start("meadow").ok);
game.GameState.data.expeditions[0].endsAt = Date.now() - 1;
game.Dungeon.completeIfReady();
assert.strictEqual(game.GameState.data.lastResult.bondFormations?.[0]?.label, "背中を預ける布陣", "Applied formation bonds reach the actual return result");
assert.strictEqual(game.GameState.data.partyHistory[0][0].bondFormations?.[0]?.sharedSorties, 20, "Applied formation bonds are preserved in expedition history");
const bondedRouteLog = game.GameState.data.lastResult.battleLog.find(entry => entry.routeEventId);
assert(bondedRouteLog?.routeBondSupportApplied && bondedRouteLog.routeBondSupportMemberIds.length === 2 && bondedRouteLog.routeBondSupportMemberNames.length === 2, "Actual return logs preserve both members of route support");
{ const parsed = transfer.parse(JSON.stringify(game.GameState.data)); assert(parsed.ok, `A real bonded return and its history survive save validation: ${parsed.message}`); }
const invalidBond = clone();
invalidBond.adventurerBonds.pairs[`${created.id}::adventurer-999`] = 1;
assert(!transfer.parse(JSON.stringify(invalidBond)).ok, "Shared-sortie records cannot refer to an unknown adventurer");
const invalidHistoryBattle = clone();
invalidHistoryBattle.partyHistory[0][0].battle.damageDealt = -1;
assert(!transfer.parse(JSON.stringify(invalidHistoryBattle)).ok, "Negative expedition-history battle totals must be rejected");
const invalidHistorySetup = clone();
invalidHistorySetup.partyHistory[0][0].partySetup[0].equipmentWeight = invalidHistorySetup.partyHistory[0][0].partySetup[0].maximumWeight + 1;
assert(!transfer.parse(JSON.stringify(invalidHistorySetup)).ok, "Invalid expedition-history loadouts must be rejected");
const invalidHistoryStory = clone();
invalidHistoryStory.partyHistory[0][0].storyMoments = [{ kind: "discovery", dungeonId: "meadow", sceneId: "missing-scene" }];
assert(!transfer.parse(JSON.stringify(invalidHistoryStory)).ok, "Unknown expedition-history story scenes must be rejected");
const invalidHistoryRoute = clone();
invalidHistoryRoute.partyHistory[0][0].routeEvents = [{ id: "missing-route-event", kind: "route", success: true, masteryApplied: false, text: "見知らぬ道中記録" }];
assert(!transfer.parse(JSON.stringify(invalidHistoryRoute)).ok, "Unknown expedition-history route events must be rejected");
const invalidHistoryMastery = clone();
invalidHistoryMastery.partyHistory[0][0].routeMasteryIds = ["missing-route-event"];
assert(!transfer.parse(JSON.stringify(invalidHistoryMastery)).ok, "Unknown expedition-history route knowledge must be rejected");
const invalidHistoryHighlight = clone();
invalidHistoryHighlight.partyHistory[0][0].memberHighlights = [{ kind: "damage", memberId: "nobody", name: "誰でもない者", value: -1 }];
assert(!transfer.parse(JSON.stringify(invalidHistoryHighlight)).ok, "Invalid expedition-history adventurer highlights must be rejected");
const invalidCharacterRecord = clone();
invalidCharacterRecord.characters[0].expeditionRecord.sorties += 1;
assert(!transfer.parse(JSON.stringify(invalidCharacterRecord)).ok, "Inconsistent adventurer expedition totals must be rejected");
const invalidRecordTitle = clone();
invalidRecordTitle.characters[0].recordTitleId = "hundred_victories";
assert(!transfer.parse(JSON.stringify(invalidRecordTitle)).ok, "Unearned personal record titles must be rejected");
const invalidRecipeResult = clone();
invalidRecipeResult.lastResult.newRecipeIds = ["missing-recipe"];
assert(!transfer.parse(JSON.stringify(invalidRecipeResult)).ok, "Unknown recipe unlocks must be rejected");
const invalidAchievementResult = clone();
invalidAchievementResult.lastResult.newAchievementIds = ["missing-achievement"];
assert(!transfer.parse(JSON.stringify(invalidAchievementResult)).ok, "Unknown achievement unlocks must be rejected");
const validSetDiscoveryResult = clone();
for (const result of [validSetDiscoveryResult.lastResult, validSetDiscoveryResult.partyResults[0]]) result.newSetDiscoveries = [{ setId: "windtrail_craft", previousCount: 1, count: 2, newBonusSkillIds: ["set_windtrail_2"], complete: false }];
assert(transfer.parse(JSON.stringify(validSetDiscoveryResult)).ok, "Equipment-set discovery progress survives save validation");
validSetDiscoveryResult.lastResult.newSetDiscoveries[0].newBonusSkillIds = [];
assert(!transfer.parse(JSON.stringify(validSetDiscoveryResult)).ok, "Missing newly crossed equipment-set bonuses are rejected");
const invalidSetDiscoveryResult = clone();
invalidSetDiscoveryResult.lastResult.newSetDiscoveries = [{ setId: "missing-set", previousCount: 0, count: 1, newBonusSkillIds: [], complete: false }];
assert(!transfer.parse(JSON.stringify(invalidSetDiscoveryResult)).ok, "Unknown equipment-set discovery records must be rejected");
const invalidAdventurerMilestone = clone();
invalidAdventurerMilestone.lastResult.newAdventurerMilestones = [{ characterId: created.id, name: created.name, milestoneIds: ["missing-milestone"] }];
assert(!transfer.parse(JSON.stringify(invalidAdventurerMilestone)).ok, "Unknown personal expedition medals must be rejected");
const invalidAdventurerRecord = clone();
invalidAdventurerRecord.lastResult.newAdventurerRecords = [{ characterId: created.id, name: created.name, improvements: [{ field: "bestDamage", previous: 999999, value: 1000000 }] }];
assert(!transfer.parse(JSON.stringify(invalidAdventurerRecord)).ok, "Impossible personal-best improvements must be rejected");
const invalidCompanionMemoryResult = clone();
invalidCompanionMemoryResult.lastResult.newCompanionMomentKeys = ["missing-moment:0"];
assert(!transfer.parse(JSON.stringify(invalidCompanionMemoryResult)).ok, "Unknown companion-memory unlocks must be rejected");
const invalidRouteEventFact = clone();
invalidRouteEventFact.story.facts.routeEvents = { "missing-route-event": { encounters: 1, successes: 1 } };
assert(!transfer.parse(JSON.stringify(invalidRouteEventFact)).ok, "Unknown route-event observations must be rejected");
const impossibleRouteEventFact = clone();
impossibleRouteEventFact.story.facts.routeEvents = { hidden_passage: { encounters: 1, successes: 2 } };
assert(!transfer.parse(JSON.stringify(impossibleRouteEventFact)).ok, "Route-event successes cannot exceed encounters");
const impossibleRumorFact = clone();
impossibleRumorFact.story.facts.routeEvents = { hidden_passage: { encounters: 1, successes: 1, rumorMatches: 2 } };
assert(!transfer.parse(JSON.stringify(impossibleRumorFact)).ok, "Rumor confirmations cannot exceed route-event encounters");
const alteredRumorReward = clone();
alteredRumorReward.story.facts.routeEvents.hidden_passage = { encounters: 1, successes: 1, rumorMatches: 1 };
alteredRumorReward.lastResult.newRumorConfirmationIds = ["hidden_passage"];
alteredRumorReward.lastResult.rumorConfirmationReward = { itemId: "guild_seal", quantity: 99 };
assert(!transfer.parse(JSON.stringify(alteredRumorReward)).ok, "An altered rumor-confirmation reward must be rejected");
const validCompanionBondResult = clone();
validCompanionBondResult.story.facts.companionMoments.push("mina_tio_machine_doubt:0", "mina_tio_machine_doubt:1");
for (const result of [validCompanionBondResult.lastResult, validCompanionBondResult.partyResults[0]]) result.completedCompanionBonds = [{ momentId: "mina_tio_machine_doubt", companionIds: ["mina", "tio"], rewardItemId: "guild_seal", rewardQuantity: 1 }];
assert(transfer.parse(JSON.stringify(validCompanionBondResult)).ok, "Completed companion bonds and their rewards survive save validation");
validCompanionBondResult.lastResult.completedCompanionBonds[0].rewardQuantity = 2;
assert(!transfer.parse(JSON.stringify(validCompanionBondResult)).ok, "Altered companion-bond rewards are rejected");
const validBattleBondResult = clone();
const bondMemberNames = [game.Characters.get(created.id).name, game.Characters.get(fellow.id).name];
const resultBond = { memberIds: [created.id, fellow.id], memberNames: bondMemberNames, positions: [0, 1], sharedSorties: 5, label: "合図の通る間合い" };
validBattleBondResult.lastResult.bondFormations = [resultBond];
validBattleBondResult.partyResults[0].bondFormations = [JSON.parse(JSON.stringify(resultBond))];
validBattleBondResult.partyHistory[0][0].bondFormations = [{ memberNames: bondMemberNames, positions: [0, 1], sharedSorties: 5, label: "合図の通る間合い" }];
{ const parsed = transfer.parse(JSON.stringify(validBattleBondResult)); assert(parsed.ok, `Battle-bond summaries survive result and history validation: ${parsed.message}`); }
validBattleBondResult.partyHistory[0][0].bondFormations[0].label = "存在しない布陣";
assert(!transfer.parse(JSON.stringify(validBattleBondResult)).ok, "Altered battle-bond tiers are rejected");
const invalidBondTierResult = clone();
invalidBondTierResult.lastResult.newAdventurerBondTiers = [{ memberIds: [created.id, fellow.id], memberNames: [created.name, fellow.name], sharedSorties: 5, routeLabel: "存在しない支え", battleLabel: "合図の通る間合い" }];
assert(!transfer.parse(JSON.stringify(invalidBondTierResult)).ok, "Altered travel-bond growth tiers are rejected");
const invalidUltraResult = clone();
invalidUltraResult.lastResult.drops.push({ itemId: "wooden_sword", quantity: 1, displayName: "未知の称号付き木の剣", qualityId: "standard", ultraRareTitleId: "missing-title" });
assert(!transfer.parse(JSON.stringify(invalidUltraResult)).ok, "Unknown ultra-rare result titles must be rejected");
const invalidTrackedResult = clone();
invalidTrackedResult.lastResult.trackedItemId = "missing-item";
invalidTrackedResult.lastResult.trackedItemQuantity = 1;
assert(!transfer.parse(JSON.stringify(invalidTrackedResult)).ok, "Unknown tracked result items must be rejected");
const completed = clone();
game.GameState.reset();
assert(transfer.restore(completed).ok);
assert(game.GameState.data.lastResult.memberReports.length === 2);
console.log("Save transfer test passed: round trip, downloads, offline expedition, results, validation, backup and storage failures");

