const fs = require("fs"), path = require("path"), vm = require("vm"), assert = require("assert");
const root = path.resolve(__dirname, ".."), storage = new Map(), nodes = new Map(), listeners = {};
let now = 1700000000000;
function node(id) {
  if (!nodes.has(id)) nodes.set(id, { innerHTML: "", textContent: "", value: "1", classList: { toggle() {} }, querySelectorAll: () => [], addEventListener() {} });
  return nodes.get(id);
}
const document = { getElementById: node, querySelector: node, querySelectorAll: () => [], addEventListener(type, handler) { listeners[type] = handler; } };
const context = vm.createContext({ window: {}, document, Date, Math, Blob, console, setTimeout: () => 0, clearTimeout() {}, setInterval: () => 0,
  localStorage: { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) } });
for (const [, file] of fs.readFileSync(path.join(root, "index.html"), "utf8").matchAll(/src="([^"]+\.js)"/g)) {
  if (file === "js/main.js") continue;
  vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context, { filename: file });
  if (file === "js/runtime.js") context.window.GameRuntime.configure({ now: () => now, random: () => .5 });
}
const game = context.window;
const html = () => node("app").innerHTML;
async function click(action, data = {}) {
  const button = { dataset: { action, ...data }, classList: { contains: () => false } };
  await listeners.click({ target: { closest: () => button } });
}
async function run() {
  game.UI.init();
  assert.strictEqual(node("status-gold").textContent, "500 G");
  assert.strictEqual(node("status-seals").textContent, "4");
  assert(/^\d{2}:\d{2}:\d{2}$/.test(node("status-clock").textContent), "Persistent status bar shows the current clock");
  assert(node("main-nav").innerHTML.includes("設定") && !node("main-nav").innerHTML.includes("商店") && !node("main-nav").innerHTML.includes("鍛冶屋") && !node("main-nav").innerHTML.includes("冒険者資料室") && !node("main-nav").innerHTML.includes("ギルド運営"), "Story staff introduce secondary facilities before their tabs appear");
  assert(node("main-nav").innerHTML.includes("mobile-primary") && node("main-nav").innerHTML.includes("mobile-secondary") && node("main-nav").innerHTML.includes("mobile-menu-button"));
  assert(node("main-nav").innerHTML.includes('data-page="home" aria-label="ホーム・続きの物語があります"') && node("main-nav").innerHTML.includes('nav-notice story') && node("main-nav").innerHTML.includes('data-page="party" aria-label="パーティ"'), "Responsive tabs expose concise accessible labels and announce unread story scenes");
  const styles = fs.readFileSync(path.join(root, "css/style.css"), "utf8");
  assert(styles.includes("position: fixed; z-index: 25") && styles.includes("grid-template-columns: repeat(3,minmax(0,1fr))") && styles.includes("mobile-nav-sheet"));
  assert(styles.includes(".global-statusbar { position: fixed") && styles.includes("bottom: calc(64px + env(safe-area-inset-bottom))"), "Persistent resources sit above the mobile navigation");
  assert(styles.includes("v0.160 mobile density pass") && styles.includes(".compact-filter-panel:not([open]) > :not(summary)") && styles.includes(".archive-tabs::-webkit-scrollbar"), "Mobile layouts condense filters and horizontally scroll secondary navigation");
  assert(html().includes("GUILD CHRONICLE"));
  assert(!node("main-nav").innerHTML.includes('data-page="dungeons"'));
  for (const text of ["facilities-panel", "セーブのバックアップ", "現在の探索", "LATEST REPORT", "ギルド記録", "commission-grid"]) assert(!html().includes(text), text);
  assert(!fs.readFileSync(path.join(root, "index.html"), "utf8").includes('data-action="reset-save"'), "Reset is not a global sidebar action");
  game.GameState.data.story.readSceneIds.push("prologue_opening"); game.UI.render();
  assert(node("main-nav").innerHTML.includes("商店") && !node("main-nav").innerHTML.includes("鍛冶屋"), "Meeting Marta unlocks only the shop");
  game.GameState.data.story.readSceneIds.push("meadow_clear"); game.UI.render();
  assert(node("main-nav").innerHTML.includes("鍛冶屋"), "Meeting Gregor unlocks the blacksmith");
  game.GameState.data.story.readSceneIds.push("whispering_brook_clear"); game.UI.render();
  assert(node("main-nav").innerHTML.includes("冒険者資料室"), "Meeting Else unlocks the archives");
  game.GameState.data.story.readSceneIds.push("roadside_clear"); game.UI.render();
  assert(node("main-nav").innerHTML.includes("ギルド運営"), "Town recognition unlocks guild management");
  await game.GameClient.execute("progress.sync");
  game.UI.render();
  await click("mobile-nav", { page: "shop" });
  assert.strictEqual(node("page-title").textContent, "商店");
  assert(html().includes("荷馬車商") && html().includes("マルタ"), "The shop keeps its story NPC visible as the proprietor");
  assert(html().includes('data-detail="daily-shop-equipment-type-') && html().includes('data-detail="standard-shop-equipment-type-'), "Daily and standard shop categories keep independent open states");
  game.UI.navigate("home");
  now += 60 * 60 * 1000;
  game.UI.navigate("guild");
  assert(html().includes("facilities-panel") && html().includes("ギルド記録") && !html().includes("commission-card"));
  for (const text of ["生産量", "保管庫", "作業速度", "facility-upgrade-panel", "data-action=\"upgrade-facility\"", "data-action=\"request-reset-facility\"", "強化 0/0回", "章を達成するごとに"]) assert(html().includes(text), `Guild facilities show ${text}`);
  assert(html().includes("facility-card is-ready") && html().includes("受取可能") && node("main-nav").innerHTML.includes("nav-notice facility"), "Completed facility production is announced");
  await click("collect-all-facilities");
  assert(!node("main-nav").innerHTML.includes("nav-notice facility"), "Collecting production clears the facility notice");
  assert(!html().includes("セーブのバックアップ") && !html().includes("GUILD CHRONICLE"));
  game.UI.navigate("archives");
  assert(html().includes("冒険者資料室") && html().includes("ギルド依頼掲示板") && html().includes("commission-card"));
  assert(html().includes("進行中 2件") && html().includes("commission-archive-panel is-locked") && html().includes("この先の依頼"), "Future commissions are condensed behind one expandable row");
  assert(html().includes('recurring-mission-board" open') && html().includes('recurring-mission-board" ><summary'), "Daily requests open first while weekly requests stay compact");
  assert(html().includes('class="archive-progress"') && html().includes("発見した品") && html().includes("遭遇した魔物") && html().includes("討伐記録") && html().includes("出会った人物") && html().includes("個人記章") && html().includes("解放した素質") && html().includes("達成した実績"), "Archives shows collection, companion, personal-record and achievement progress without revealing unknown entries");
  assert(html().includes("archive-tab-notice request"), "Claimable request rewards are announced");
  await click("archive-view", { view: "observations" });
  assert(html().includes("観察日記") && html().includes("迷った時ほど、先に傷を見る") && html().includes("回復 → 呪文 → 技 → 攻撃"));
  assert(html().includes("observation-new-badge") && html().includes("archive-tab-notice observation"), "Unread journal pages are announced");
  await click("observation-read", { note: "choosing_an_action" });
  assert(!html().includes("observation-new-badge") && !html().includes("archive-tab-notice observation") && html().includes("archive-tab-notice request"), "Reading clears only the journal notice");
  await click("archive-view", { view: "commissions" });
  await click("claim-recurring-mission", { group: "daily", mission: "login" });
  assert(!html().includes("archive-tab-notice request"), "Claiming the ready reward clears its notice");
  await click("archive-view", { view: "observations" });
  assert(html().includes("未整理の観察記録") && html().includes("灯りの鉱山を攻略すると記録されます"));
  assert(!html().includes("同じ剣を百本、床に並べた夜"), "Locked journal titles remain undisclosed");
  game.Items.add("sticky_fluid", 1);
  game.Items.add("wooden_sword", 1, { source: "drop", qualityId: "standard", ultraRareTitleId: "worldbreaker", modifiers: { hp: 0, attack: 0, defense: 0 } });
  game.UI.render();
  assert(html().includes("archive-tab-notice discovery"), "A first item discovery is announced in the archive tabs");
  await click("archive-view", { view: "items" });
  assert(!html().includes("archive-tab-notice discovery"), "Opening the item codex marks its discoveries as read");
  assert(html().includes("アイテム図鑑") && html().includes("名を持つ逸品の記録") && html().includes("1 / 8") && html().includes("★天地を砕く") && html().includes("世界を砕く力") && html().includes("物理攻撃威力が18%増加する") && html().includes("？？？ ×7") && html().includes("武器・剣") && html().includes("武器・杖") && html().includes("防具・布装備") && html().includes("防具・盾") && html().includes(">素材<") && html().includes("木の剣") && html().includes("最高品質") && html().includes("？？？") && html().includes("codex-unknown-stack") && !html().includes("commission-card"));
  assert((html().match(/codex-unknown-stack/g) || []).length <= 11, "Unknown items are condensed to at most one card per encyclopedia category");
  assert(html().includes("入手元を確認") && html().includes("風鳴りの草原") && html().includes("スライムを討伐") && html().includes("通常・魔境・神域"));
  assert(html().includes('data-action="track-item" data-item="sticky_fluid"'));
  await click("track-item", { item: "sticky_fluid" });
  assert(html().includes("現在の探索目標") && html().includes("ねばねばした液体") && html().includes('id="item-target-form"') && html().includes('data-action="clear-tracked-item"'));
  await listeners.submit({ target: { id: "item-target-form", dataset: { item: "sticky_fluid" }, elements: { targetQuantity: { value: "8" } } }, preventDefault() {} });
  assert(html().includes("0 / 8") && game.Encyclopedia.trackedTarget().quantity === 8, "The codex updates a target's required quantity");
  await click("clear-tracked-item");
  assert(html().includes("発見済みの品から一つ選ぶ"));
  await click("archive-view", { view: "monsters" });
  assert(html().includes("モンスター図鑑") && html().includes("風鳴りの草原") && html().includes("未遭遇") && !html().includes("ギルド依頼掲示板"));
  const observation = (drops, difficultySkillIds = []) => ({ incomingAttempts: 1, incomingHits: 1, difficultySkillIds, drops });
  game.Encyclopedia.recordBattle({ slime: 1 }, { slime: 1 }, { slime: observation(["sticky_fluid", "wooden_sword"]) }, "normal");
  game.Encyclopedia.recordBattle({ slime: 1 }, {}, { slime: observation(["abyss_slime_core"], ["viscous_wave"]) }, "abyss");
  game.Encyclopedia.recordBattle({ slime: 1 }, { slime: 1 }, { slime: observation(["divine_slime_core"]) }, "divine");
  game.UI.navigate("archives");
  assert(html().includes("通常") && html().includes("魔境のスライム") && html().includes("神域のスライム"));
  assert(html().includes("ねばねばした液体") && html().includes("魔境の粘核") && html().includes("神域の虹粘核"));
  assert(html().includes("粘液波・3T") && html().includes("固有技 未確認 2種"), "Observed skills are revealed after a failed battle while unobserved divine skills remain hidden");
  assert(!html().includes("木の剣"), "Shop equipment must not be listed in monster drop records");
  await click("archive-view", { view: "origins" });
  assert(html().includes("冒険者体系") && html().includes("職業15・種族15・生まれ15"));
  for (const text of ["戦士", "攻めの心得", "人間", "血統の力", "平凡な家", "幼き日の鍛錬", "能力補正", "装備適性", "習得スキル", "初期", "Lv.100"]) assert(html().includes(text), text);
  assert(html().includes("Lv.1") && html().includes("未解放") && html().includes("達成で解放"));
  assert(!html().includes("commission-card") && !html().includes("codex-grid"));
  await click("archive-view", { view: "companions" });
  assert(html().includes("人物録"), "The companion ledger can be opened from the archive tabs");
  assert(html().includes("0 / 8人加入"), "The companion ledger reports the joined roster");
  assert(html().includes("未遭遇の人物 ×8"), "Future companions are condensed into one concealed row");
  assert(!html().includes("地脈を聴く鍛冶師"), "Unknown companion identities stay concealed before their chapters");
  game.GameState.data.story.joinedCompanionIds = ["mina", "tio"];
  game.GameState.data.story.facts.companionMoments = ["mina_tio_machine_doubt:0"];
  game.UI.render();
  assert(html().includes("同行の記録") && html().includes("ミナとティオ") && html().includes("機械の迷い") && html().includes("1篇"), "Witnessed pair scenes form a compact relationship record");
  assert(!html().includes("記録にない道具"), "Undiscovered companion relationships remain concealed");
  game.GameState.data.story.facts.companionMoments.push("mina_tio_machine_doubt:1");
  game.UI.render();
  assert(html().includes("is-bonded") && html().includes("縁が結ばれた"), "A fully witnessed relationship is distinguished without exposing unfinished pairs");
  game.GameState.data.story.joinedCompanionIds = [];
  game.GameState.data.story.facts.companionMoments = [];
  game.UI.render();
  await click("archive-view", { view: "achievements" });
  assert(html().includes("実績の記録") && html().includes("最初の契約") && html().includes("星なき夜を越えて") && html().includes("星後を歩く者") && html().includes('data-achievement="five_reaches_wedge"') && html().includes("未記入の実績") && !html().includes("五界を分かつ楔") && html().includes("achievement-meter"));
  assert(!html().includes("commission-card") && !html().includes("codex-grid"));
  game.UI.navigate("settings");
  for (const action of ["export-save", "import-save", "export-before-import", "reset-save"]) assert(html().includes('data-action="' + action + '"'));
  assert(html().includes('<details class="code-unlock-card'), "Access-code settings use compact expandable rows");
  assert(html().includes('data-feature="party_expansion_trial"') && html().includes('data-feature="half_exploration_trial"'), "Each unlock has its own code input area");
  for (const feature of ["double_experience_trial", "double_gold_trial", "double_quality_trial", "double_item_rate_trial"]) assert(html().includes(`data-feature="${feature}"`));
  assert(!html().includes("facilities-panel") && !html().includes("LATEST REPORT"));
  game.GameState.data.gold = 100000;
  game.UI.navigate("shop");
  node(".main-area").scrollTop = 460;
  await click("buy", { item: "wooden_sword" });
  assert.strictEqual(node(".main-area").scrollTop, 460, "Buying standard stock should preserve the current shop position");
  game.UI.navigate("settings");
  await click("reset-save"); await click("close-modal");
  const a = require("./helpers").createCharacter(game, "第一隊", "warrior").id;
  game.Characters.get(a).level = 30;
  game.Party.toggle(a);
  game.UI.navigate("home");
  assert(html().includes('data-action="open-story-reader"') && html().includes("未読の物語"), "Home promotes the current story instead of exposing its full text inline");
  const introductoryEpisodeId = game.Story.pendingEpisode().id;
  await click("open-story-reader");
  assert(node("modal-root").innerHTML.includes("story-reader-scroll") && node("modal-root").innerHTML.includes("読み終える") && node("modal-root").innerHTML.includes("disabled"), "The dedicated reader groups scenes and requires reaching its ending");
  assert(node("modal-root").innerHTML.includes("story-reader-setting") && node("modal-root").innerHTML.includes("story-reader-dialogue") && node("modal-root").innerHTML.includes("受付係") && node("modal-root").innerHTML.includes("マスター") && node("modal-root").innerHTML.includes("依頼と帰還を預かる者"), "Story scenes mix world description with identifiable character conversations without addressing the player as 'you'");
  await click("finish-story-reader", { episode: introductoryEpisodeId });
  assert(html().includes('data-action="party-view" data-view="adventure"'));
  await click("party-view", { view: "adventure" });
  await click("quick-start-party", { party: "0" });
  assert.strictEqual(node("page-title").textContent, "パーティ");
  assert(html().includes('data-countdown="0"') && html().includes("第一隊"));
  now += 30000; await game.GameClient.execute("expedition.collect");
  assert(!game.Story.canEnter("whispering_brook"), "Clearing a route alone does not skip its story transition");
  game.UI.navigate("home");
  const meadowEpisodeId = game.Story.pendingEpisode().id;
  await click("open-story-reader");
  assert(node("modal-root").innerHTML.includes("風鳴りの草原") && node("modal-root").innerHTML.includes("囁きの小川"), "The reader joins the completed route and next destination into one substantial episode");
  await click("finish-story-reader", { episode: meadowEpisodeId });
  assert(game.Story.canEnter("whispering_brook"), "Finishing the story opens the next main route");
  require("./helpers").completeThrough(game, "seal");
  game.GameState.data.story.facts.companionMoments.push("mina_earth_echo:0");
  game.UI.navigate("archives");
  await click("archive-view", { view: "companions" });
  assert(html().includes("2 / 8人加入") && html().includes("ミナ") && html().includes("地脈聴き") && html().includes("エレナ") && html().includes("欠け星の天球儀") && html().includes("未遭遇の人物 ×6"), "The ledger shows companions who joined when their starring chapter opened");
  assert(html().includes("人物の歩み") && html().includes("companion-growth-timeline") && html().includes("出会い") && html().includes("現在"), "The companion ledger shows the reached growth-stage history without revealing future stages");
  assert(html().includes("旅の記憶") && html().includes("地脈の響き") && html().includes("地脈の響きから崩れにくい道"), "The companion ledger only reveals travel scenes that were actually witnessed");
  game.GameState.data.unlockedPartyCount = 2;
  const b = require("./helpers").createCharacter(game, "第二隊", "mage").id;
  game.Party.toggle(b, 1);
  await game.GameClient.execute("expedition.start", { dungeonId: "cave", partyIndex: 1 });
  game.GameState.data.partyResults[0].newRecipeIds = ["forge_greenwood_staff"];
  game.GameState.data.partyResults[0].companionAdvancements = [{ companionId: "mina", stageId: "free_hammer", previousStageId: "base" }];
  game.GameState.data.partyResults[0].completedCompanionBonds = [{ momentId: "mina_tio_machine_doubt", companionIds: ["mina", "tio"], rewardItemId: "guild_seal", rewardQuantity: 1 }];
  game.UI.navigate("party");
  await click("party-view", { view: "results" });
  assert(html().includes("第1パーティの直近の探索結果") && html().includes("最新の探索報告"));
  assert(game.GameState.data.partyResults[0].newRecipeIds?.length && html().includes("NEW RECIPES") && html().includes("鍛冶屋で確認"), "New recipes appear in the expedition result");
  assert(html().includes("COMPANION GROWTH") && html().includes("坑道崩し") && html().includes("解縛の鍛槌") && html().includes("機巧師の誓い"), "Companion growth reports name replaced and newly learned skills");
  assert(html().includes("TRAVEL BOND") && html().includes("同行の縁が深まりました") && html().includes("ミナとティオ") && html().includes("ギルド印章 +1"), "A completed companion relationship and its keepsake appear in the return report");
  await click("open-new-recipes", { recipes: "forge_greenwood_staff" });
  assert.strictEqual(node("page-title").textContent, "鍛冶屋");
  assert(html().includes("製作レシピ") && html().includes("鍛冶メニュー") && html().includes("今回解放された1件を表示中") && html().includes("newly-unlocked"));
  game.UI.navigate("party");
  await click("party-back");
  assert(html().includes('data-countdown="1"'), "Party top includes the other party countdown");
  await click("select-party", { party: "1" });
  assert(html().includes('data-countdown="1"') && html().includes("第二隊"));
  await click("party-view", { view: "results" });
  assert(html().includes("第2パーティの直近の探索結果") && !html().includes("最新の探索報告"));
  game.UI.navigate("home");
  assert(!html().includes("第一隊") && !html().includes('data-countdown=') && !html().includes("最新の探索報告"));
  const before = JSON.stringify(game.GameState.data);
  game.UI.navigate("guild"); game.UI.navigate("archives"); game.UI.navigate("settings"); game.UI.navigate("party");
  assert.strictEqual(JSON.stringify(game.GameState.data), before, "Navigation must not mutate saved progress");
  console.log("UI pages test passed: story-only home, archives with requests/adventurer system/codices, guild facilities/logs, settings/save actions, departure routing, party report isolation and non-mutating navigation");
}
run().catch(error => { console.error(error); process.exitCode = 1; });
