const fs = require("fs"), vm = require("vm"), path = require("path"), assert = require("assert");
const root = path.resolve(__dirname, ".."), storage = new Map();
let now = 1700000000000, failSave = false;
function load() {
  const context = vm.createContext({ window: {}, Date, Math, Blob, console: { ...console, warn() {} } });
  const scripts = Array.from(fs.readFileSync(path.join(root, "index.html"), "utf8").matchAll(/src="([^"]+\.js)"/g), match => match[1]).filter(file => !["js/ui.js", "js/main.js"].includes(file));
  for (const file of scripts) {
    vm.runInContext(fs.readFileSync(path.join(root, file), "utf8"), context, { filename: file });
    if (file === "js/runtime.js") context.window.GameRuntime.configure({ now: () => now, random: () => .5 });
    if (file === "js/storage.js") context.window.SaveStorage.use({ get: key => storage.get(key) || null, set: (key, value) => { if (failSave) throw Error("full"); storage.set(key, value); }, remove: key => storage.delete(key) });
  }
  return context.window;
}
let game = load();
const enhance = (id, level) => game.GameClient.execute("equipment.upgrade", { instanceId: id, expectedLevel: level });
async function run() {
  assert.strictEqual(game.Upgrades.limit(), 0);
  const initial = JSON.stringify(game.GameState.data);
  assert(!(await enhance("item-1", 0)).ok);
  assert.strictEqual(JSON.stringify(game.GameState.data), initial);
  const id = require("./helpers").createCharacter(game, "強化役", "warrior", "human", "common").id;
  game.Party.toggle(id); game.Items.equip(id, "item-1"); game.Items.equip(id, "item-2");
  game.Story.recordDeparture("meadow");
  assert.strictEqual(game.Upgrades.limit(), 1);
  game.GameState.data.gold = 10000;
  for (const material of ["iron_ore", "magic_stone", "star_shard"]) game.Items.add(material, 100);
  game.Items.setLocked("item-1", true);
  const before = game.Items.effects(game.Items.getInstance("item-1"));
  const originalStats = game.Characters.stats(game.Characters.get(id));
  const quote = game.Upgrades.quote("item-1"), gold = game.GameState.data.gold;
  const duplicates = await Promise.all([enhance("item-1", 0), enhance("item-1", 0)]);
  assert.strictEqual(duplicates.filter(result => result.ok).length, 1);
  assert.strictEqual(game.Items.getInstance("item-1").upgradeLevel, 1);
  assert.strictEqual(game.GameState.data.gold, gold - quote.gold);
  assert.strictEqual(game.Items.count("iron_ore"), 99);
  assert(game.Items.getInstance("item-1").locked);
  const after = game.Items.effects(game.Items.getInstance("item-1"));
  assert.strictEqual(after.attack, before.attack + 2);
  assert.strictEqual(after.weight, before.weight);
  assert(game.Characters.stats(game.Characters.get(id)).attack > originalStats.attack);
  assert(game.Items.displayName(game.Items.getInstance("item-1")).endsWith("＋1"));
  assert(!(await enhance("item-1", 1)).ok);
  assert((await game.GameClient.execute("preset.save", { slot: 0, name: "強化前の構成" })).ok);
  require("./helpers").completeThrough(game, "roadside");
  assert.strictEqual(game.Upgrades.limit(), 3);
  const rollback = JSON.stringify(game.GameState.data);
  failSave = true; assert(!(await enhance("item-1", 1)).ok); failSave = false;
  assert.strictEqual(JSON.stringify(game.GameState.data), rollback);
  game.GameState.data.gold = 0; assert(!game.Upgrades.quote("item-1").ok); game.GameState.data.gold = 10000;
  const ore = game.Items.count("iron_ore"); game.Items.remove("iron_ore", ore);
  assert(!game.Upgrades.quote("item-1").ok); game.Items.add("iron_ore", ore);
  assert((await enhance("item-1", 1)).ok);
  assert(!(await enhance("item-1", 1)).ok, "Stale confirmation cannot spend resources again.");
  const thirdQuote = game.Upgrades.quote("item-1");
  assert.deepStrictEqual(Array.from(thirdQuote.addedSkills, skill => skill.id), ["sword_training"]);
  const thirdResult = await enhance("item-1", 2);
  assert(thirdResult.ok && thirdResult.addedSkills[0].id === "sword_training" && thirdResult.message.includes("剣術"));
  assert(game.EquipmentSkills.ids(game.Items.getInstance("item-1")).includes("sword_training"));
  assert(!(await enhance("item-1", 3)).ok);
  require("./helpers").completeChapter(game, "seal");
  assert.strictEqual(game.Upgrades.limit(), 5);
  assert.strictEqual(game.Upgrades.quote("item-1").materials.magic_stone, 1);
  assert((await enhance("item-1", 3)).ok); assert((await enhance("item-1", 4)).ok);
  require("./helpers").completeChapter(game, "starfall");
  assert.strictEqual(game.Upgrades.limit(), 7);
  assert.strictEqual(game.Upgrades.quote("item-1").materials.star_shard, 1);
  const sixthQuote = game.Upgrades.quote("item-1");
  assert.deepStrictEqual(Array.from(sixthQuote.addedSkills, skill => skill.id), ["sword_mastery"]);
  assert((await enhance("item-1", 5)).ok); assert((await enhance("item-1", 6)).ok);
  assert(!(await enhance("item-1", 7)).ok);
  const armorBefore = game.Items.effects(game.Items.getInstance("item-2"));
  assert((await enhance("item-2", 0)).ok);
  const armorAfter = game.Items.effects(game.Items.getInstance("item-2"));
  assert.strictEqual(armorAfter.defense, armorBefore.defense + 2);
  assert.strictEqual(armorAfter.hp, armorBefore.hp + 3);
  assert.strictEqual(armorAfter.weight, armorBefore.weight);
  assert((await game.GameClient.execute("preset.apply", { slot: 0 })).ok);
  assert.strictEqual(game.Items.getInstance("item-1").upgradeLevel, 7);
  const unique = game.Items.add("golem_plate", 1, { source: "drop" }).instances[0];
  const uniqueEffects = game.Items.effects(unique), uniqueDefinition = JSON.stringify(game.GameData.items.golem_plate);
  assert((await enhance(unique.id, 0)).ok);
  assert.strictEqual(game.Items.effects(unique).defense, uniqueEffects.defense + 2);
  assert.strictEqual(JSON.stringify(game.GameData.items.golem_plate), uniqueDefinition);
  assert(unique.locked);
  game.GameState.save(); game = load();
  assert.strictEqual(game.Items.getInstance("item-1").upgradeLevel, 7);
  const saved = JSON.stringify(game.GameState.data);
  assert(game.SaveTransfer.parse(saved).ok);
  for (const value of [-1, 1.5, 8, "3"]) {
    const bad = JSON.parse(saved); bad.inventory.equipment[0].upgradeLevel = value;
    assert(!game.SaveTransfer.parse(JSON.stringify(bad)).ok);
  }
  const old = JSON.parse(saved); old.inventory.equipment.forEach(item => delete item.upgradeLevel);
  assert(!game.SaveTransfer.parse(JSON.stringify(old)).ok);
  const wrongChapter = JSON.parse(saved); wrongChapter.story.completed = ["prologue"];
  assert(!game.SaveTransfer.parse(JSON.stringify(wrongChapter)).ok);
  assert((await game.GameClient.execute("expedition.start", { dungeonId: "meadow" })).ok);
  const snapshot = JSON.stringify(game.GameState.data.expeditions[0].partySnapshot);
  assert(!(await enhance("item-2", 1)).ok);
  assert.strictEqual(JSON.stringify(game.GameState.data.expeditions[0].partySnapshot), snapshot);
  now += 30000; await game.GameClient.execute("expedition.collect");
  assert((await enhance("item-2", 1)).ok);
  assert(game.SaveTransfer.parse(JSON.stringify(game.GameState.data)).ok);
  game.GameState.reset(); assert.strictEqual(game.Upgrades.limit(), 0);
  console.log("Upgrades test passed: chapter caps 0/1/3/5/7, cost/bonus/weight, atomic rollback, stale/double prevention, locked/unique gear, presets, persistence/import validation and expedition protection");
}
run().catch(error => { console.error(error); process.exitCode = 1; });
