(function () {
  "use strict";

  window.GameUIViews = window.GameUIViews || {};

  function originBonuses(context, character) {
    const buffs = window.Characters.profile(character);
    const percent = value => `${Math.round(value * 100)}%`;
    const affinities = (types, values) => Object.entries(types).map(([id, name]) => `<span>${name} <strong>${percent(values[id] || 1)}</strong></span>`).join("");
    return `<div class="origin-bonuses"><div class="origin-source-list">${window.Characters.origins(character).map(origin => `<p><strong>${origin.name}</strong>：${origin.description}</p>`).join("")}</div><div class="bonus-chips"><span>基礎HP ${percent(buffs.hpMultiplier)}</span><span>基礎攻撃 ${percent(buffs.attackMultiplier)}</span><span>基礎防御 ${percent(buffs.defenseMultiplier)}</span><span>重量上限 ${percent(buffs.weightMultiplier)}</span><span>スキル威力 ${percent(buffs.skillPower)}</span><span>回復威力 ${percent(buffs.healingPower)}</span></div><div class="bonus-chips"><span>基礎魔法攻撃 ${percent(buffs.magicAttackMultiplier)}</span><span>基礎魔法防御 ${percent(buffs.magicDefenseMultiplier)}</span><span>基礎魔法回復 ${percent(buffs.magicHealingMultiplier)}</span><span>命中補正 ${Math.round(buffs.hitBonus * 100)}pt</span><span>回避補正 ${Math.round(buffs.evasionBonus * 100)}pt</span></div><div class="affinity-row"><b>武器適性</b>${affinities(window.GameData.weaponTypes, buffs.weaponAffinity)}</div><div class="affinity-row"><b>防具適性</b>${affinities(window.GameData.armorTypes, buffs.armorAffinity)}</div><p class="origin-rule">能力倍率と適性は種族×職業×生まれで乗算。適性は装備性能へ適用し、装備重量は変わりません。</p></div>`;
  }

  function card(context, character) {
    const stat = window.Characters.stats(character);
    const identity = window.Characters.origins(character).map(origin => origin.name).join(" / ");
    const currentWeight = window.Characters.equipmentWeight(character), maxWeight = window.Characters.maxWeight(character);
    return `<article class="character-card compact-record"><button type="button" class="record-summary character-open-row" data-action="open-character" data-character="${character.id}">${context.portraitImage(character, true)}<span class="record-name"><strong>${context.escape(character.name)}</strong><small>${context.escape(window.Characters.jobName(character))} · Lv.${character.level} · ${context.escape(identity)}</small></span><span class="record-stats"><b>HP ${stat.hp}</b><b>攻 ${stat.attack}</b><b>防 ${stat.defense}</b><b>攻撃${stat.attackCount}回</b><b>重 ${currentWeight}/${maxWeight}</b></span><span class="power-tag">戦力 ${Math.round(stat.attack * 2.1 + stat.defense * 1.6 + stat.hp * .34)}</span><span class="record-chevron" aria-hidden="true">›</span></button></article>`;
  }

  function detail(context, character) {
    const { equipmentSkillBadges, escape, extraStats, portraitImage, statBar } = context;
    const stat = window.Characters.stats(character);
    const next = window.Characters.expToNext(character.level);
    const equipped = character.equipment.map(window.Items.getInstance).filter(Boolean);
    const currentWeight = window.Characters.equipmentWeight(character), maxWeight = window.Characters.maxWeight(character);
    const weightPercent = Math.min(100, currentWeight / maxWeight * 100);
    const gearCard = instance => {
      const type = window.Items.template(instance.templateId).type;
      const label = type === "weapon" ? "武器" : "防具";
      const effect = window.Characters.equipmentEffects(character, instance);
      const range = type === "weapon" ? (window.Items.template(instance.templateId).range === "ranged" ? "遠距離" : "近接") : "";
      return `<div class="equipment-slot"><span>${label}${range ? ` · ${range}` : ""}</span><strong class="quality-${instance.qualityId}">${escape(window.Items.displayName(instance))}</strong><small>${effect.attack ? `攻+${effect.attack} ` : ""}${effect.defense ? `防+${effect.defense} ` : ""}${effect.hp ? `HP+${effect.hp} ` : ""}${effect.attackCount ? `攻撃回数${effect.attackCount > 0 ? "+" : ""}${effect.attackCount} ` : ""}重${effect.weight}</small>${equipmentSkillBadges(instance)}<div class="slot-actions"><button class="text-button muted-action" data-action="unequip" data-character="${character.id}" data-instance="${instance.id}">外す</button></div></div>`;
    };
    const learned = window.Characters.learnedSkills(character), progression = window.Characters.skillProgression(character);
    const skillList = progression.map(skill => { const acquired = skill.initial || character.level >= skill.level; return `<span class="skill-chip ${acquired ? "learned" : "locked"}" title="${escape(skill.sources.join("・") + "：" + skill.description)}">${skill.initial ? "初期" : acquired ? "✧" : `Lv.${skill.level}`} ${escape(window.GameData.skillCategories[skill.category] || "技")} · ${escape(skill.name)}</span>`; }).join("");
    const buffs = window.Characters.profile(character), identity = window.Characters.origins(character).map(origin => origin.name).join(" / ");
    const careerAction = character.career ? `<span class="badge good">転職済み</span>` : `<button class="button ghost" data-action="request-class-change" data-character="${character.id}">転職先を確認</button>`;
    return `<section class="panel character-detail-card"><div class="character-detail-summary">${portraitImage(character, true)}<span class="record-name"><strong>${escape(character.name)}</strong><small>${escape(window.Characters.jobName(character))} · Lv.${character.level} · ${escape(identity)}</small></span><span class="power-tag">戦力 ${Math.round(stat.attack * 2.1 + stat.defense * 1.6 + stat.hp * .34)}</span></div><div class="character-detail-actions"><button class="button primary" data-action="open-equipment" data-character="${character.id}">装備を変更</button>${careerAction}</div><div class="record-detail"><div class="character-stats">${statBar("HP", stat.hp, Math.max(100, stat.hp), stat.hp)}${statBar("攻撃", stat.attack, 50, stat.attack)}${statBar("防御", stat.defense, 45, stat.defense)}${statBar("EXP", character.exp, next, `${character.exp}/${next}`)}</div>${extraStats(stat)}<p class="character-identity">${escape(identity)}</p><div class="combat-traits"><span>速度 <strong>${stat.speed}</strong></span><span>攻撃回数 <strong>${stat.attackCount}</strong></span><span>会心率 <strong>${Math.round(stat.criticalRate * 100)}%</strong></span><span>習得済み <strong>${learned.length}/${progression.length}</strong></span></div><div class="skill-list">${skillList}</div><details class="origin-details"><summary>出自と補正を確認</summary>${originBonuses(context, character)}</details>${character.career ? `<p class="career-history"><strong>転職済み</strong>：${escape(window.GameData.jobs[character.career.previousJobId].name)} Lv.${character.career.levelBefore} → ${escape(window.Characters.jobName(character))}（前職の習得スキルを保持）</p>` : ""}${character.talentId ? `<p class="small-note">応募時の得意分野：${escape(window.GameData.recruitmentTalents[character.talentId].name)}（基礎能力に反映済み）</p>` : ""}${window.Characters.specialEquipment(character).map(id => `<p class="special-effect"><strong>${escape(window.GameData.items[id].name)}</strong>：${escape(window.GameData.items[id].effectDescription)}</p>`).join("")}<div class="weight-capacity"><div><span>装備重量</span><strong>${currentWeight} / ${maxWeight}</strong></div><div class="weight-bar ${weightPercent > 85 ? "near-limit" : ""}"><i style="width:${weightPercent}%"></i></div><small>基準 約${window.Characters.equipmentCapacityAtLevel(character.level).toFixed(1)}点分（平均重量${window.Characters.averageEquipmentWeight().toFixed(1)}） · 組み合わせ補正 ×${buffs.weightMultiplier.toFixed(2)}</small></div><p class="small-note">装備 ${equipped.length}点・個数制限なし。近接・遠距離併用時は両方の隊列補正を乗算します。</p><div class="equipment-slots">${equipped.map(gearCard).join("") || '<p class="empty-line">未装備</p>'}</div></div></section>`;
  }

  function page(context) {
    const { applicantCard, characterView, empty, escape, recruitmentRequirementPreview, recruitmentSummary } = context;
    const characters = window.GameState.data.characters, pending = window.Recruitment.state().pending;
    const fields = window.GameData.recruitment.fields.map(field => {
      const unlocked = window.Recruitment.unlocked(field);
      const options = Object.values(window.GameData[field.table]).filter(window.Recruitment.entryUnlocked).map(entry => `<option value="${entry.id}">${escape(entry.name)}</option>`).join("");
      return `<label for="recruit-${field.id}">${escape(field.name)}<select id="recruit-${field.id}" name="${field.id}" data-recruitment-field ${unlocked ? "" : "disabled"}><option value="any">指定なし</option>${unlocked ? options : ""}</select><small>${escape(field.condition)}</small></label>`;
    }).join("");
    const pendingQuote = pending ? window.Recruitment.postingQuote(pending.requirements) : null;
    const initialRequirements = Object.fromEntries(window.GameData.recruitment.fields.map(field => [field.id, "any"]));
    const initialQuote = window.Recruitment.postingQuote(initialRequirements);
    const sealName = escape(window.GameData.items[window.GameData.recruitment.postingCost.itemId].name);
    const recruitment = pending ? `<section class="panel recruitment-board" tabindex="-1"><span class="label">GUILD APPLICATIONS</span><h3>応募者の選考 · ${pending.candidates.length}人</h3><p>${escape(recruitmentSummary(pending.requirements))}</p><p>募集費用：${sealName}×${pendingQuote.quantity}（使用済み）。能力・適性・スキル・雇用費を比較して1人を選んでください。雇用すると契約金を消費し、残りの応募者は退出します。応募者は保存済みで、リロードしても変わりません。</p><button class="button ghost" data-action="request-dismiss-applicants">全員を見送る</button></section><div class="card-grid applicant-grid">${pending.candidates.map(candidate => applicantCard(candidate, pending.requirements)).join("")}</div>` : `<section class="panel creation-panel"><div class="section-heading"><div><span class="label">GUILD RECRUITMENT</span><h3>ギルドの募集要項</h3></div></div><p>条件は希望です。2〜5人が応募し、1人を選んで雇用します。希望条件には原則80%で沿いますが、個体差があります。希望職業は最低1人が応募します。</p><form id="recruitment-form"><div class="creation-fields">${fields}</div><section class="recruitment-requirement-preview" id="recruitment-requirement-preview" aria-live="polite">${recruitmentRequirementPreview(initialRequirements)}</section><div class="recruitment-post-cost ${initialQuote.affordable ? "" : "is-short"}" id="recruitment-post-cost"><strong>募集費用：${sealName}×<span data-recruitment-cost>${initialQuote.quantity}</span></strong><span>所持 <b data-recruitment-owned>${initialQuote.owned}</b>個 ／ 募集後 <b data-recruitment-after>${Math.max(0, initialQuote.owned - initialQuote.quantity)}</b>個</span><small><b data-recruitment-selections>${initialQuote.selections}</b>項目指定 · <span data-recruitment-applicants>応募予定 ${initialQuote.applicants[0]}〜${initialQuote.applicants[1]}人</span></small></div><p class="small-note">募集費用は指定なしで印章1個、希望を1項目追加するごとに印章が1個増えます。募集後に全員を見送っても印章は戻りません。雇用時には別途、職業・種族・初期能力に応じた契約金を消費します。</p><button class="button primary" id="recruitment-submit" type="submit" ${initialQuote.affordable ? "" : "disabled"}>${initialQuote.affordable ? "募集を出して応募者を待つ" : `${sealName}が不足しています`}</button></form></section>`;
    const query = characterView.query.trim().toLocaleLowerCase("ja");
    const filtered = characters.filter(character => (characterView.job === "all" || character.jobId === characterView.job) && (!query || character.name.toLocaleLowerCase("ja").includes(query) || window.Characters.jobName(character).toLocaleLowerCase("ja").includes(query))).sort((a, b) => characterView.sort === "name" ? a.name.localeCompare(b.name, "ja") : characterView.sort === "newest" ? b.createdAt - a.createdAt : b.level - a.level || a.name.localeCompare(b.name, "ja"));
    const pageSize = 20, pages = Math.max(1, Math.ceil(filtered.length / pageSize));
    characterView.page = Math.min(characterView.page, pages - 1);
    const visible = filtered.slice(characterView.page * pageSize, (characterView.page + 1) * pageSize);
    const jobs = Object.values(window.GameData.jobs).map(job => `<option value="${job.id}" ${characterView.job === job.id ? "selected" : ""}>${escape(job.name)}</option>`).join("");
    const directory = characters.length ? `<section class="panel character-directory"><form id="character-directory-form" class="directory-controls"><label>検索<input id="character-directory-query" value="${escape(characterView.query)}" placeholder="名前・職業"></label><label>職業<select data-character-filter="job"><option value="all">全職業</option>${jobs}</select></label><label>並び順<select data-character-filter="sort"><option value="level">レベル順</option><option value="name" ${characterView.sort === "name" ? "selected" : ""}>名前順</option><option value="newest" ${characterView.sort === "newest" ? "selected" : ""}>加入順</option></select></label><button class="button secondary" type="submit">検索</button></form><p class="compact-list-guide">行を押すと能力・スキル・装備を表示します。</p><div class="character-directory-list">${visible.map(character => card(context, character)).join("") || '<p class="empty-line">条件に合う冒険者はいません。</p>'}</div><nav class="pagination" aria-label="所属冒険者のページ"><button class="button ghost" data-action="character-page" data-page="${characterView.page - 1}" ${characterView.page === 0 ? "disabled" : ""}>前へ</button><span>${characterView.page + 1} / ${pages}ページ · ${filtered.length}人</span><button class="button ghost" data-action="character-page" data-page="${characterView.page + 1}" ${characterView.page >= pages - 1 ? "disabled" : ""}>次へ</button></nav></section>` : empty("所属冒険者がいません", "募集要項を出して、最初の仲間を雇用してください。");
    return recruitment + `<section class="section-heading roster-heading"><div><span class="label">GUILD MEMBERS</span><h3>所属冒険者 · ${characters.length}人</h3></div></section>${directory}`;
  }

  window.GameUIViews.characters = { card, detail, originBonuses, page };
})();
