(function () {
  "use strict";

  window.GameUIViews = window.GameUIViews || {};

  function originBonuses(context, character) {
    const buffs = window.Characters.profile(character);
    const percent = value => `${Math.round(value * 100)}%`;
    const affinities = (types, values) => Object.entries(types).map(([id, name]) => `<span>${name} <strong>${percent(values[id] || 1)}</strong></span>`).join("");
    return `<div class="origin-bonuses"><div class="origin-source-list">${window.Characters.origins(character).map(origin => `<p><strong>${origin.name}</strong>：${origin.description}</p>`).join("")}</div><div class="bonus-chips"><span>基礎HP ${percent(buffs.hpMultiplier)}</span><span>基礎攻撃 ${percent(buffs.attackMultiplier)}</span><span>基礎防御 ${percent(buffs.defenseMultiplier)}</span><span>重量上限 ${percent(buffs.weightMultiplier)}</span><span>スキル威力 ${percent(buffs.skillPower)}</span><span>回復威力 ${percent(buffs.healingPower)}</span></div><div class="bonus-chips"><span>基礎魔法攻撃 ${percent(buffs.magicAttackMultiplier)}</span><span>基礎魔法防御 ${percent(buffs.magicDefenseMultiplier)}</span><span>基礎魔法回復 ${percent(buffs.magicHealingMultiplier)}</span><span>命中補正 ${Math.round(buffs.hitBonus * 100)}pt</span><span>回避補正 ${Math.round(buffs.evasionBonus * 100)}pt</span></div><div class="affinity-row"><b>武器適性</b>${affinities(window.GameData.derived.weaponTypes, buffs.weaponAffinity)}</div><div class="affinity-row"><b>防具適性</b>${affinities(window.GameData.derived.armorTypes, buffs.armorAffinity)}</div><p class="origin-rule">能力倍率と適性は種族×職業×生まれで乗算。適性は装備性能へ適用し、装備重量は変わりません。</p></div>`;
  }

  function card(context, character) {
    const stat = window.Characters.stats(character);
    const identity = window.Characters.origins(character).map(origin => origin.name).join(" / ");
    const companion = window.Characters.companionDefinition(character);
    const recordTitle = window.Characters.recordTitle(character);
    const currentWeight = window.Characters.equipmentWeight(character), maxWeight = window.Characters.maxWeight(character);
    const specialties = window.Characters.fieldSpecialties(character);
    const specialty = specialties.length ? `${specialties.slice(0, 2).map(entry => entry.name).join("・")}${specialties.length > 2 ? `・ほか${specialties.length - 2}種` : ""}` : "";
    return `<article class="character-card compact-record"><button type="button" class="record-summary character-open-row" data-action="open-character" data-character="${character.id}">${context.portraitImage(character, true)}<span class="record-name"><strong>${context.escape(character.name)}${companion ? ' <em class="badge good">物語加入</em>' : ""}</strong><small>${context.escape(window.Characters.jobName(character))} · Lv.${character.level} · ${context.escape(identity)}${specialty ? ` · 探索 ${context.escape(specialty)}` : ""}</small>${recordTitle ? `<em class="adventurer-record-title">${context.escape(recordTitle.icon)} ${context.escape(recordTitle.name)}</em>` : ""}</span><span class="record-stats"><b>HP ${stat.hp}</b><b>攻 ${stat.attack}</b><b>防 ${stat.defense}</b><b>攻撃${stat.attackCount}回</b><b>重 ${currentWeight}/${maxWeight}</b></span><span class="power-tag">戦力 ${Math.round(stat.attack * 2.1 + stat.defense * 1.6 + stat.hp * .34)}</span><span class="record-chevron" aria-hidden="true">›</span></button></article>`;
  }

  function detail(context, character) {
    const { equipmentSkillBadges, escape, extraStats, portraitImage, statBar } = context;
    const stat = window.Characters.stats(character);
    const next = window.Characters.expToNext(character.level);
    const equipped = character.equipment.map(window.Items.getInstance).filter(Boolean);
    const currentWeight = window.Characters.equipmentWeight(character), maxWeight = window.Characters.maxWeight(character);
    const weightPercent = Math.min(100, currentWeight / maxWeight * 100);
    const gearCard = instance => {
      const type = window.Items.template(instance.templateId).type;
      const label = type === "weapon" ? "武器" : "防具";
      const effect = window.Characters.equipmentEffects(character, instance);
      const range = type === "weapon" ? (window.Items.template(instance.templateId).range === "ranged" ? "遠距離" : "近接") : "";
      return `<div class="equipment-slot"><span>${label}${range ? ` · ${range}` : ""}</span><strong class="quality-${instance.qualityId}">${escape(window.Items.displayName(instance))}</strong><small>${effect.attack ? `攻+${effect.attack} ` : ""}${effect.defense ? `防+${effect.defense} ` : ""}${effect.hp ? `HP+${effect.hp} ` : ""}${effect.attackCount ? `攻撃回数${effect.attackCount > 0 ? "+" : ""}${effect.attackCount} ` : ""}重${effect.weight}</small>${equipmentSkillBadges(instance)}<div class="slot-actions"><button class="text-button muted-action" data-action="unequip" data-character="${character.id}" data-instance="${instance.id}">外す</button></div></div>`;
    };
    const learned = window.Characters.learnedSkills(character), progression = window.Characters.skillProgression(character);
    const skillList = progression.map(skill => { const acquired = skill.initial || character.level >= skill.level; const cooldown = skill.activation?.type === "active" ? ` 再使用：${skill.activation.cooldownTurns}ターン。` : ""; return `<span class="skill-chip ${acquired ? "learned" : "locked"}" title="${escape(skill.sources.join("・") + "：" + skill.description + cooldown)}">${skill.initial ? "初期" : acquired ? "✧" : `Lv.${skill.level}`} ${escape(window.GameData.config.skillCategories[skill.category] || "技")} · ${escape(skill.name)}</span>`; }).join("");
    const buffs = window.Characters.profile(character), identity = window.Characters.origins(character).map(origin => origin.name).join(" / ");
    const companion = window.Characters.companionDefinition(character);
    const recordTitle = window.Characters.recordTitle(character);
    const expeditionRecord = window.Characters.expeditionRecord(character);
    const routeExperience = window.Characters.routeExperience(character);
    const fieldSpecialties = window.Characters.fieldSpecialties(character);
    const sharedSorties = window.Characters.sharedSorties(character);
    const expeditionMilestones = window.Characters.expeditionMilestones(character);
    const earnedMilestones = expeditionMilestones.filter(milestone => milestone.complete);
    const nextMilestone = expeditionMilestones.filter(milestone => !milestone.complete).sort((a, b) => b.ratio - a.ratio || a.target - b.target)[0];
    const number = value => Number(value || 0).toLocaleString("ja-JP");
    const milestoneBadges = earnedMilestones.length ? earnedMilestones.map(milestone => `<button type="button" class="record-medal-choice ${recordTitle?.id === milestone.id ? "is-selected" : ""}" title="${escape(milestone.description)}" data-action="select-record-title" data-character="${character.id}" data-milestone="${milestone.id}"><b>${escape(milestone.icon)}</b>${escape(milestone.name)}${recordTitle?.id === milestone.id ? " · 表示中" : ""}</button>`).join("") + (recordTitle ? `<button type="button" class="record-medal-clear" data-action="select-record-title" data-character="${character.id}">表示を外す</button>` : "") : '<small>まだ記章はありません。</small>';
    const nextMilestoneHtml = nextMilestone ? `<p><span>次の記録</span><strong>${escape(nextMilestone.name)}</strong><small>${number(nextMilestone.current)} / ${number(nextMilestone.target)}</small></p>` : '<p class="all-earned"><strong>すべての記章を獲得しました</strong></p>';
    const routeExperienceEntries = [...routeExperience.map(entry => ({ label: entry.label, count: entry.count })), ...(expeditionRecord.treasureOpenings ? [{ label: "封印箱を開けた", count: expeditionRecord.treasureOpenings }] : [])];
    const specialtySummary = fieldSpecialties.length ? `<p class="character-field-specialties"><small>身についた得意分野</small><strong>${fieldSpecialties.map(entry => `${escape(entry.icon)} ${escape(entry.name)}`).join("・")}</strong></p>` : "";
    const bondDefinitions = new Map((window.GameData.config.explorationEvents?.adventurerBondMoments || []).map(moment => [moment.id, moment]));
    const rememberedCompanions = sharedSorties.filter(entry => entry.memoryIds.length);
    const travelCompanions = sharedSorties.length ? `<section class="character-route-experience character-travel-companions"><strong>共に歩いた仲間</strong><div>${sharedSorties.slice(0, 6).map(entry => { const memoryTitles = entry.memoryIds.map(id => bondDefinitions.get(id)?.title).filter(Boolean); return `<span><small>${escape(entry.name)}</small><b>${number(entry.count)}回${memoryTitles.length ? ` · 記憶${memoryTitles.length}篇` : ""}</b></span>`; }).join("")}</div>${sharedSorties.length > 6 ? `<small>ほか${sharedSorties.length - 6}人との同行記録があります。</small>` : ""}${rememberedCompanions.length ? '<button type="button" class="text-button" data-action="open-adventurer-bonds">二人の記憶を資料室で読む</button>' : ""}</section>` : "";
    const routeExperienceHtml = (routeExperienceEntries.length ? `<section class="character-route-experience"><strong>道中で身についた経験</strong>${specialtySummary}<div>${routeExperienceEntries.map(entry => `<span><small>${escape(entry.label)}</small><b>${number(entry.count)}回</b></span>`).join("")}</div></section>` : "") + travelCompanions;
    const expeditionLedger = `<details class="character-expedition-record"><summary><span><strong>遠征の足跡</strong><small>${expeditionRecord.sorties ? `出撃 ${number(expeditionRecord.sorties)}回・攻略 ${number(expeditionRecord.victories)}回・記章 ${earnedMilestones.length}/${expeditionMilestones.length}` : "まだ出撃記録はありません"}</small></span><i aria-hidden="true">›</i></summary><div><span><small>出撃</small><strong>${number(expeditionRecord.sorties)}</strong></span><span><small>攻略</small><strong>${number(expeditionRecord.victories)}</strong></span><span><small>撤退</small><strong>${number(expeditionRecord.retreats)}</strong></span><span><small>突破戦闘</small><strong>${number(expeditionRecord.encounterClears)}</strong></span><span><small>道中の難所を解決</small><strong>${number(expeditionRecord.routeSuccesses)}</strong></span><span><small>封印箱を開封</small><strong>${number(expeditionRecord.treasureOpenings)}</strong></span><span><small>連携探索に参加</small><strong>${number(expeditionRecord.teamSurveys)}</strong></span><span><small>累計実ダメージ</small><strong>${number(expeditionRecord.damageDealt)}</strong></span><span><small>累計実回復</small><strong>${number(expeditionRecord.healingDone)}</strong></span><span><small>累計被ダメージ</small><strong>${number(expeditionRecord.damageTaken)}</strong></span><span><small>会心</small><strong>${number(expeditionRecord.criticalHits)}</strong></span><span><small>一遠征の最高与ダメージ</small><strong>${number(expeditionRecord.bestDamage)}</strong></span><span><small>一遠征の最高回復</small><strong>${number(expeditionRecord.bestHealing)}</strong></span><span><small>生還した最大被ダメージ</small><strong>${number(expeditionRecord.bestEndurance)}</strong></span><span><small>戦闘不能帰還</small><strong>${number(expeditionRecord.knockouts)}</strong></span></div>${routeExperienceHtml}<section class="character-record-medals"><div>${milestoneBadges}</div>${nextMilestoneHtml}</section></details>`;
    const careerAction = character.career ? `<span class="badge good">転職済み</span>` : `<button class="button ghost" data-action="request-class-change" data-character="${character.id}">転職先を確認</button>`;
    return `<section class="panel character-detail-card"><div class="character-detail-summary">${portraitImage(character, true)}<span class="record-name"><strong>${escape(character.name)}${companion ? ' <em class="badge good">物語加入</em>' : ""}</strong><small>${escape(window.Characters.jobName(character))} · Lv.${character.level} · ${escape(identity)}</small>${recordTitle ? `<em class="adventurer-record-title">${escape(recordTitle.icon)} ${escape(recordTitle.name)}</em>` : ""}</span><span class="power-tag">戦力 ${Math.round(stat.attack * 2.1 + stat.defense * 1.6 + stat.hp * .34)}</span></div>${companion ? `<p class="special-effect"><strong>${escape(companion.title)}</strong>：${escape(companion.description)}</p>` : ""}<div class="character-detail-actions"><button class="button primary" data-action="open-equipment" data-character="${character.id}">装備を変更</button>${careerAction}</div><div class="record-detail"><div class="character-stats">${statBar("HP", stat.hp, Math.max(100, stat.hp), stat.hp)}${statBar("攻撃", stat.attack, 50, stat.attack)}${statBar("防御", stat.defense, 45, stat.defense)}${statBar("EXP", character.exp, next, `${character.exp}/${next}`)}</div>${extraStats(stat)}<p class="character-identity">${escape(identity)}</p><div class="combat-traits"><span>速度 <strong>${stat.speed}</strong></span><span>攻撃回数 <strong>${stat.attackCount}</strong></span><span>会心率 <strong>${Math.round(stat.criticalRate * 100)}%</strong></span><span>習得済み <strong>${learned.length}/${progression.length}</strong></span></div>${expeditionLedger}<div class="skill-list">${skillList}</div><details class="origin-details"><summary>出自と補正を確認</summary>${originBonuses(context, character)}</details>${character.career ? `<p class="career-history"><strong>転職済み</strong>：${escape(window.GameData.jobs[character.career.previousJobId].name)} Lv.${character.career.levelBefore} → ${escape(window.Characters.jobName(character))}（前職の習得スキルを保持）</p>` : ""}${character.talentId ? `<p class="small-note">応募時の得意分野：${escape(window.GameData.recruitmentTalents[character.talentId].name)}（基礎能力に反映済み）</p>` : ""}${window.Characters.specialEquipment(character).map(id => `<p class="special-effect"><strong>${escape(window.GameData.items[id].name)}</strong>：${escape(window.GameData.items[id].effectDescription)}</p>`).join("")}<div class="weight-capacity"><div><span>装備重量</span><strong>${currentWeight} / ${maxWeight}</strong></div><div class="weight-bar ${weightPercent > 85 ? "near-limit" : ""}"><i style="width:${weightPercent}%"></i></div><small>基準 約${window.Characters.equipmentCapacityAtLevel(character.level).toFixed(1)}点分（平均重量${window.Characters.averageEquipmentWeight().toFixed(1)}） · 組み合わせ補正 ×${buffs.weightMultiplier.toFixed(2)}</small></div><p class="small-note">装備 ${equipped.length}点・個数制限なし。近接・遠距離併用時は両方の隊列補正を乗算します。</p><div class="equipment-slots">${equipped.map(gearCard).join("") || '<p class="empty-line">未装備</p>'}</div></div></section>`;
  }

  function page(context) {
    const { applicantCard, characterView, empty, escape, recruitmentRequirementPreview, recruitmentSummary } = context;
    const characters = window.GameState.data.characters, pending = window.Recruitment.state().pending;
    const fields = window.GameData.config.recruitment.fields.map(field => {
      const unlocked = window.Recruitment.unlocked(field);
      const options = Object.values(window.GameData[field.table]).filter(window.Recruitment.entryUnlocked).map(entry => `<option value="${entry.id}">${escape(entry.name)}</option>`).join("");
      return `<label for="recruit-${field.id}">${escape(field.name)}<select id="recruit-${field.id}" name="${field.id}" data-recruitment-field ${unlocked ? "" : "disabled"}><option value="any">指定なし</option>${unlocked ? options : ""}</select><small>${escape(field.condition)}</small></label>`;
    }).join("");
    const pendingQuote = pending ? window.Recruitment.postingQuote(pending.requirements) : null;
    const initialRequirements = Object.fromEntries(window.GameData.config.recruitment.fields.map(field => [field.id, "any"]));
    const initialQuote = window.Recruitment.postingQuote(initialRequirements);
    const sealName = escape(window.GameData.items[window.GameData.config.recruitment.postingCost.itemId].name);
    const recruitment = pending ? `<section class="panel recruitment-board" tabindex="-1"><span class="label">GUILD APPLICATIONS</span><h3>応募者の選考 · ${pending.candidates.length}人</h3><p>${escape(recruitmentSummary(pending.requirements))}</p><p>募集費用：${sealName}×${pendingQuote.quantity}（使用済み）。能力・適性・スキル・雇用費を比較して1人を選んでください。雇用すると契約金を消費し、残りの応募者は退出します。応募者は保存済みで、リロードしても変わりません。</p><button class="button ghost" data-action="request-dismiss-applicants">全員を見送る</button></section><div class="card-grid applicant-grid">${pending.candidates.map(candidate => applicantCard(candidate, pending.requirements)).join("")}</div>` : `<section class="panel creation-panel"><div class="section-heading"><div><span class="label">GUILD RECRUITMENT</span><h3>ギルドの募集要項</h3></div></div><p>条件は希望です。2〜5人が応募し、1人を選んで雇用します。希望条件には原則80%で沿いますが、個体差があります。希望職業は最低1人が応募します。</p><form id="recruitment-form"><div class="creation-fields">${fields}</div><section class="recruitment-requirement-preview" id="recruitment-requirement-preview" aria-live="polite">${recruitmentRequirementPreview(initialRequirements)}</section><div class="recruitment-post-cost ${initialQuote.affordable ? "" : "is-short"}" id="recruitment-post-cost"><strong>募集費用：${sealName}×<span data-recruitment-cost>${initialQuote.quantity}</span></strong><span>所持 <b data-recruitment-owned>${initialQuote.owned}</b>個 ／ 募集後 <b data-recruitment-after>${Math.max(0, initialQuote.owned - initialQuote.quantity)}</b>個</span><small><b data-recruitment-selections>${initialQuote.selections}</b>項目指定 · <span data-recruitment-applicants>応募予定 ${initialQuote.applicants[0]}〜${initialQuote.applicants[1]}人</span></small></div><p class="small-note">募集費用は指定なしで印章1個、希望を1項目追加するごとに印章が1個増えます。募集後に全員を見送っても印章は戻りません。雇用時には別途、職業・種族・初期能力に応じた契約金を消費します。</p><button class="button primary" id="recruitment-submit" type="submit" ${initialQuote.affordable ? "" : "disabled"}>${initialQuote.affordable ? "募集を出して応募者を待つ" : `${sealName}が不足しています`}</button></form></section>`;
    const query = characterView.query.trim().toLocaleLowerCase("ja");
    const fieldCount = character => window.Characters.fieldSpecialties(character).length;
    const fieldTotal = character => window.Characters.routeExperience(character).reduce((sum, entry) => sum + entry.count, 0) + window.Characters.expeditionRecord(character).treasureOpenings;
    const filtered = characters.filter(character => {
      const specialties = window.Characters.fieldSpecialties(character);
      return (characterView.job === "all" || character.jobId === characterView.job)
        && (characterView.specialty === "all" || specialties.some(entry => entry.id === characterView.specialty))
        && (!query || character.name.toLocaleLowerCase("ja").includes(query) || window.Characters.jobName(character).toLocaleLowerCase("ja").includes(query)
          || specialties.some(entry => `${entry.name}${entry.label}${entry.title}`.toLocaleLowerCase("ja").includes(query)));
    }).sort((a, b) => characterView.sort === "name" ? a.name.localeCompare(b.name, "ja") : characterView.sort === "newest" ? b.createdAt - a.createdAt : characterView.sort === "field" ? fieldCount(b) - fieldCount(a) || fieldTotal(b) - fieldTotal(a) || b.level - a.level : b.level - a.level || a.name.localeCompare(b.name, "ja"));
    const pageSize = 20, pages = Math.max(1, Math.ceil(filtered.length / pageSize));
    characterView.page = Math.min(characterView.page, pages - 1);
    const visible = filtered.slice(characterView.page * pageSize, (characterView.page + 1) * pageSize);
    const jobEntries = Object.values(window.GameData.jobs).map(job => [job.id, job.name]);
    const jobs = jobEntries.map(([id, name]) => `<option value="${id}" ${characterView.job === id ? "selected" : ""}>${escape(name)}</option>`).join("");
    const sortEntries = [["level", "レベル順"], ["field", "探索経験順"], ["name", "名前順"], ["newest", "加入順"]];
    const specialtyEntries = [...(window.GameData.config.explorationEvents?.routeEvents || []).map(entry => [entry.id, entry.name]), ["treasure_opening", "開錠"]];
    const specialties = specialtyEntries.map(([id, name]) => `<option value="${id}" ${characterView.specialty === id ? "selected" : ""}>${escape(name)}</option>`).join("");
    const selectedJob = characterView.job === "all" ? "全職業" : jobEntries.find(([id]) => id === characterView.job)?.[1] || "職業";
    const selectedSpecialty = characterView.specialty === "all" ? "全探索経験" : specialtyEntries.find(([id]) => id === characterView.specialty)?.[1] || "探索経験";
    const selectedSort = sortEntries.find(([id]) => id === characterView.sort)?.[1] || "レベル順";
    const directorySummary = [characterView.query ? `検索「${characterView.query}」` : "", selectedJob, selectedSpecialty, selectedSort].filter(Boolean).join("・");
    const directory = characters.length ? `<section class="panel character-directory"><details class="compact-filter-panel directory-filter-panel" data-detail="character-directory-filters"><summary><strong>絞り込み・並べ替え</strong><small>${escape(directorySummary)}</small><i aria-hidden="true">›</i></summary><form id="character-directory-form" class="directory-controls"><label>検索<input id="character-directory-query" value="${escape(characterView.query)}" placeholder="名前・職業・探索経験"></label><label>職業<select data-character-filter="job"><option value="all">全職業</option>${jobs}</select></label><label>探索経験<select data-character-filter="specialty"><option value="all">すべて</option>${specialties}</select></label><label>並び順<select data-character-filter="sort">${sortEntries.map(([id, name]) => `<option value="${id}" ${characterView.sort === id ? "selected" : ""}>${name}</option>`).join("")}</select></label><button class="button secondary" type="submit">検索</button></form></details><p class="compact-list-guide">行を押すと能力・スキル・装備を表示します。</p><div class="character-directory-list">${visible.map(character => card(context, character)).join("") || '<p class="empty-line">条件に合う冒険者はいません。</p>'}</div><nav class="pagination" aria-label="所属冒険者のページ"><button class="button ghost" data-action="character-page" data-page="${characterView.page - 1}" ${characterView.page === 0 ? "disabled" : ""}>前へ</button><span>${characterView.page + 1} / ${pages}ページ · ${filtered.length}人</span><button class="button ghost" data-action="character-page" data-page="${characterView.page + 1}" ${characterView.page >= pages - 1 ? "disabled" : ""}>次へ</button></nav></section>` : empty("所属冒険者がいません", "募集要項を出して、最初の仲間を雇用してください。");
    return recruitment + `<section class="section-heading roster-heading"><div><span class="label">GUILD MEMBERS</span><h3>所属冒険者 · ${characters.length}人</h3></div></section>${directory}`;
  }

  window.GameUIViews.characters = { card, detail, originBonuses, page };
})();
